(function defineKageArsenal(global) {
  "use strict";

  const SLOT_DEFINITIONS = Object.freeze([
    { id: "primary", label: "ARME PRINCIPALE", shortLabel: "PRINCIPALE" },
    { id: "secondary", label: "ARME SECONDAIRE", shortLabel: "SECONDAIRE" },
    { id: "ranged", label: "PROJECTILE / TIR", shortLabel: "DISTANCE" },
  ]);

  const CATEGORY_DEFINITIONS = Object.freeze([
    { id: "all", label: "TOUT" },
    { id: "katana", label: "KATANAS" },
    { id: "shortBlade", label: "LAMES COURTES" },
    { id: "polearm", label: "ARMES D’HAST" },
    { id: "heavy", label: "ARMES LOURDES" },
    { id: "staff", label: "BÂTONS" },
    { id: "flexible", label: "CHAÎNES" },
    { id: "bow", label: "ARCS" },
    { id: "firearm", label: "ARMES À FEU" },
    { id: "throwing", label: "PROJECTILES" },
    { id: "fan", label: "ÉVENTAILS" },
  ]);

  const RARITY_LABELS = Object.freeze({
    common: "USÉ",
    uncommon: "ÉPROUVÉ",
    rare: "MAGISTRAL",
    epic: "HÉRITAGE",
    legendary: "LÉGENDAIRE",
    tainted: "SOUILLÉ",
  });

  const STAT_DEFINITIONS = Object.freeze([
    { id: "power", label: "PUISSANCE", higherIsBetter: true },
    { id: "speed", label: "CADENCE", higherIsBetter: true },
    { id: "reach", label: "ALLONGE", higherIsBetter: true },
    { id: "kiCost", label: "COÛT DE KI", higherIsBetter: false },
    { id: "posture", label: "POSTURE", higherIsBetter: true },
    { id: "control", label: "CONTRÔLE", higherIsBetter: true },
  ]);

  const GENERATED_KATANA_ROOT = "assets/modular/fps/player/akio/weapons";
  const MODULAR_WEAPON_ROOT = "assets/modular/weapons";
  const SHINOBI_COMPONENT_ROOT = `${MODULAR_WEAPON_ROOT}/components/shinobi`;

  function clampStat(value) {
    return Math.max(0, Math.min(100, Number(value) || 0));
  }

  function stats(power, speed, reach, kiCost, posture, control, multipliers = {}) {
    const armorMultiplier = Number(multipliers.armor ?? 1);
    return Object.freeze({
      power: clampStat(power),
      speed: clampStat(speed),
      reach: clampStat(reach),
      kiCost: clampStat(kiCost),
      posture: clampStat(posture),
      control: clampStat(control),
      flesh: Number(multipliers.flesh ?? 1),
      armor: armorMultiplier,
      armorPenetration: clampStat(
        multipliers.armorPenetration
        ?? Math.round((armorMultiplier - 0.5) * 75),
      ),
      spirit: Number(multipliers.spirit ?? 1),
      boss: Number(multipliers.boss ?? 1),
    });
  }

  function passive(id, name, description, trigger, effect, value, cooldown = 0) {
    return Object.freeze({
      id,
      name,
      description,
      trigger,
      effect,
      value: Number(value),
      cooldown: Number(cooldown),
    });
  }

  function unlock(type, label, value = null) {
    return Object.freeze({ type, label, value });
  }

  function existingSprites(pack, id) {
    const sprite = `${MODULAR_WEAPON_ROOT}/${pack}/${id}.png`;
    return Object.freeze({
      preview: sprite,
      side: sprite,
      fps: sprite,
    });
  }

  function katanaSprites(id) {
    return Object.freeze({
      preview: `${GENERATED_KATANA_ROOT}/${id}/weapon.png`,
      side: `${GENERATED_KATANA_ROOT}/${id}/weapon.png`,
      fps: `${GENERATED_KATANA_ROOT}/${id}/weapon.png`,
    });
  }

  function shinobiSprites(id, componentBased = false) {
    const componentPreview = {
      kunai: "kunai-ring.png",
      "hira-shuriken": "hira-shuriken-square.png",
      "bo-shuriken": "bo-shuriken.png",
      makibishi: "makibishi.png",
      "kyoketsu-shoge": "kyoketsu-shoge-blade.png",
      "kusari-kunai": "kunai-ring.png",
      "nunchaku-ryukyu": "nunchaku-handle-a.png",
    };
    const preview = `${SHINOBI_COMPONENT_ROOT}/${componentPreview[id] || `${id}.png`}`;
    return Object.freeze({
      preview,
      side: preview,
      fps: preview,
    });
  }

  function component(file) {
    return `${SHINOBI_COMPONENT_ROOT}/${file}`;
  }

  function componentPart(file, anchor = [0.5, 0.5]) {
    return Object.freeze({
      file,
      anchor: Object.freeze([...anchor]),
    });
  }

  function chainComponents(id, parts) {
    const recipeFiles = {
      chigiriki: {
        handle: componentPart(`${MODULAR_WEAPON_ROOT}/ranged/jo.png`, [0.5, 0.5]),
        weight: componentPart(component("fundo-weight.png"), [0.5, 0.12]),
      },
      kusarigama: {
        blade: componentPart(component("kusarigama-kama.png"), [0.24, 0.84]),
        weight: componentPart(component("fundo-weight.png"), [0.5, 0.12]),
      },
      manrikigusari: {
        weightA: componentPart(component("fundo-weight.png"), [0.5, 0.12]),
        weightB: componentPart(component("fundo-weight.png"), [0.5, 0.12]),
      },
      "kyoketsu-shoge": {
        blade: componentPart(component("kyoketsu-shoge-blade.png"), [0.78, 0.2]),
        ring: componentPart(component("kyoketsu-terminal-ring.png"), [0.5, 0.5]),
      },
      "kusari-kunai": {
        kunai: componentPart(component("kunai-ring.png"), [0.78, 0.18]),
        weight: componentPart(component("fundo-weight.png"), [0.5, 0.12]),
      },
      "nunchaku-ryukyu": {
        handleA: componentPart(component("nunchaku-handle-a.png"), [0.5, 0.08]),
        handleB: componentPart(component("nunchaku-handle-b.png"), [0.5, 0.08]),
      },
    };
    const recipe = recipeFiles[id] || {};
    return Object.freeze({
      root: SHINOBI_COMPONENT_ROOT,
      link: componentPart(component("chain-link-small.png"), [0.5, 0.5]),
      ...Object.fromEntries(parts.map((part) => [
        part,
        recipe[part] || componentPart(component(`${part}.png`)),
      ])),
    });
  }

  function weapon(definition) {
    const entry = {
      playable: true,
      renderMode: "rigid",
      ammoType: null,
      maxAmmo: 0,
      unlockedByDefault: false,
      ...definition,
    };
    if (entry.family === "katana" && entry.animationProfile === "blade") {
      entry.animationProfile = "katana";
    }
    if (!Array.isArray(entry.anchor)) {
      const profileAnchors = {
        katana: [0.26, 0.52],
        blade: [0.25, 0.76],
        polearm: [0.24, 0.78],
        heavy: [0.25, 0.77],
        staff: [0.3, 0.66],
        flexible: [0.28, 0.56],
        bow: [0.7, 0.46],
        firearm: [0.3, 0.62],
        throwing: [0.5, 0.5],
        fan: [0.5, 0.88],
      };
      entry.anchor = Object.freeze([
        ...(profileAnchors[entry.animationProfile] || profileAnchors.blade),
      ]);
    }
    entry.slots = Object.freeze([...entry.slots]);
    entry.tags = Object.freeze([...(entry.tags || [])]);
    entry.unlock = entry.unlock || unlock("chapter", "À découvrir dans la campagne");
    entry.rarityLabel = RARITY_LABELS[entry.rarity] || String(entry.rarity || "").toUpperCase();
    return Object.freeze(entry);
  }

  const weapons = [
    weapon({
      id: "01-kurokage",
      name: "Kurokage",
      subtitle: "L’ombre noire",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "furtivité", "bakufu"],
      rarity: "rare",
      lore: "Sabre d’un messager du bakufu, marqué par les routes de quarantaine.",
      gameplay: "Une lame équilibrée qui récompense les attaques portées dans le dos.",
      stats: stats(57, 69, 53, 27, 52, 76, { flesh: 1.05, armor: 0.9, spirit: 1 }),
      passive: passive("shadow-step", "Pas de l’ombre", "Détection réduite et dégâts accrus dans le dos.", "onBackstab", "backstabDamage", 1.1),
      unlock: unlock("starter", "Confié à Akio par le shogun"),
      unlockedByDefault: true,
      sprites: katanaSprites("01-kurokage"),
    }),
    weapon({
      id: "02-shogun-no-in",
      name: "Shōgun no In",
      subtitle: "Le sceau du shogun",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "parade", "résolution"],
      rarity: "legendary",
      lore: "Une lame de présentation attestant l’ordre d’éradication venu d’Edo.",
      gameplay: "La parade parfaite renforce brièvement Akio.",
      stats: stats(62, 58, 56, 31, 67, 65, { flesh: 1, armor: 1.03, spirit: 1.08 }),
      passive: passive("bakufu-authority", "Autorité du bakufu", "Une parade parfaite accorde 20 % de résistance pendant deux secondes.", "onPerfectParry", "damageResistance", 0.2, 3),
      unlock: unlock("chapter", "Récompense du chapitre 2", 2),
      sprites: katanaSprites("02-shogun-no-in"),
    }),
    weapon({
      id: "03-hinezumi",
      name: "Hinezumi",
      subtitle: "Le rat de feu",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "vitesse", "esquive"],
      rarity: "uncommon",
      lore: "Retrouvé intact sous les poutres d’un relais incendié.",
      gameplay: "Une esquive parfaite accélère les attaques suivantes.",
      stats: stats(48, 86, 49, 21, 43, 73, { flesh: 1.06, armor: 0.78, spirit: 0.96 }),
      passive: passive("ember-flight", "Fuite des braises", "Une esquive parfaite augmente la cadence de 15 % pendant trois secondes.", "onPerfectDodge", "attackSpeed", 1.15, 5),
      unlock: unlock("secret", "Secret du relais incendié", "kurokawa-burned-relay"),
      sprites: katanaSprites("03-hinezumi"),
    }),
    weapon({
      id: "04-shirogane",
      name: "Shirogane",
      subtitle: "L’acier d’argent",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "armure", "parade"],
      rarity: "epic",
      lore: "Une lame de Mino sortie de son coffre lorsque les morts forcèrent le domaine.",
      gameplay: "Fenêtre de parade plus large et meilleur rendement contre l’armure.",
      stats: stats(64, 61, 54, 30, 78, 71, { flesh: 0.98, armor: 1.18, spirit: 0.94 }),
      passive: passive("immaculate-edge", "Fil immaculé", "La fenêtre de parade parfaite est élargie de 18 %.", "passive", "parryWindow", 1.18),
      unlock: unlock("artisan", "Forgeron Kaji — restauration", "kaji"),
      sprites: katanaSprites("04-shirogane"),
    }),
    weapon({
      id: "05-yomibane",
      name: "Yomibane",
      subtitle: "La plume de Yomi",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "exécution", "esprit"],
      rarity: "rare",
      lore: "Sabre funéraire des gardiens qui brûlaient les contaminés.",
      gameplay: "Les exécutions restaurent une partie de la résolution.",
      stats: stats(55, 65, 52, 26, 58, 72, { flesh: 1, armor: 0.88, spirit: 1.22 }),
      passive: passive("last-breath", "Dernier souffle", "Exécuter un infecté étourdi rend huit points de résolution.", "onExecution", "restoreResolve", 8, 4),
      unlock: unlock("boss", "Dépouille de la Miko Tsukikage", "mb-04-miko-tsukikage"),
      sprites: katanaSprites("05-yomibane"),
    }),
    weapon({
      id: "06-kegare-kiri",
      name: "Kegare-kiri",
      subtitle: "Le tranche-souillure",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "lourd", "infecté"],
      rarity: "uncommon",
      lore: "Une lame raccourcie et repolie après les premiers assauts.",
      gameplay: "Excellent contre les infectés lourds et les membres mutés.",
      stats: stats(74, 45, 58, 38, 76, 49, { flesh: 1.14, armor: 1.12, spirit: 0.77, boss: 1.08 }),
      passive: passive("eradication-tool", "Outil d’éradication", "Les cibles lourdes subissent 22 % de dégâts supplémentaires.", "onDamage", "heavyTargetDamage", 1.22),
      unlock: unlock("contract", "Contrat des fosses de quarantaine", "quarantine-pits"),
      sprites: katanaSprites("06-kegare-kiri"),
    }),
    weapon({
      id: "07-takekaze",
      name: "Takekaze",
      subtitle: "Le vent du bambou",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "économie", "mobilité"],
      rarity: "common",
      lore: "Un sabre rural conçu pour être réparé loin des grandes forges.",
      gameplay: "Les attaques légères et les esquives consomment moins de Ki.",
      stats: stats(46, 78, 50, 18, 41, 82, { flesh: 1, armor: 0.8, spirit: 1 }),
      passive: passive("reed-flexibility", "Souplesse du roseau", "Le coût des attaques légères est réduit de 12 %.", "passive", "lightAttackKiCost", 0.88),
      unlock: unlock("chapter", "Sanctuaire du bambou brisé", 2),
      sprites: katanaSprites("07-takekaze"),
    }),
    weapon({
      id: "08-raijin-no-tsume",
      name: "Raijin no Tsume",
      subtitle: "La griffe de Raijin",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "lourd", "posture"],
      rarity: "epic",
      lore: "Une lame d’Echizen dont le hamon anguleux nourrit la légende.",
      gameplay: "Les attaques lourdes chargées brisent rapidement la posture.",
      stats: stats(69, 52, 57, 35, 89, 58, { flesh: 1, armor: 1.16, spirit: 0.91, boss: 1.06 }),
      passive: passive("guard-breaker", "Brise-garde", "Les attaques lourdes infligent 25 % de dégâts de posture supplémentaires.", "onHeavyHit", "postureDamage", 1.25),
      unlock: unlock("boss", "Vaincre le Hatamoto Inazuma", "mb-11-hatamoto-inazuma"),
      sprites: katanaSprites("08-raijin-no-tsume"),
    }),
    weapon({
      id: "09-akatsuki",
      name: "Akatsuki",
      subtitle: "L’aube",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "offensive", "santé"],
      rarity: "rare",
      lore: "Porté lors de la reprise d’une forteresse contaminée à l’aube.",
      gameplay: "Akio frappe plus fort tant qu’il reste presque indemne.",
      stats: stats(67, 63, 55, 29, 62, 68, { flesh: 1.11, armor: 0.96, spirit: 1 }),
      passive: passive("first-ray", "Premier rayon", "Les dégâts augmentent de 15 % au-dessus de 80 % de santé.", "onDamage", "highHealthDamage", 1.15),
      unlock: unlock("rank", "Obtenir le rang A au chapitre 3", "chapter-3-a"),
      sprites: katanaSprites("09-akatsuki"),
    }),
    weapon({
      id: "10-mujo",
      name: "Mujō",
      subtitle: "L’impermanence",
      category: "katana",
      family: "katana",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "parade", "survie"],
      rarity: "legendary",
      lore: "Un vieux sabre réparé, passé entre les mains de rōnin oubliés.",
      gameplay: "Les parades deviennent plus rentables lorsque la santé est basse.",
      stats: stats(60, 56, 53, 25, 84, 79, { flesh: 1, armor: 1.05, spirit: 1.1, boss: 1.08 }),
      passive: passive("nothing-remains", "Rien ne demeure", "Sous 30 % de santé, une parade parfaite rend dix points de Ki.", "onPerfectParry", "lowHealthRestoreKi", 10, 2),
      unlock: unlock("ngplus", "Héritage du mode Nouvelle Partie +", "ng-plus"),
      sprites: katanaSprites("10-mujo"),
    }),

    weapon({
      id: "bokuto",
      name: "Bokutō",
      subtitle: "Sabre d’entraînement",
      category: "shortBlade",
      family: "trainingBlade",
      animationProfile: "blade",
      slots: ["primary", "secondary"],
      tags: ["contondant", "étourdissement", "dōjō"],
      rarity: "common",
      lore: "Un sabre de bois abandonné dans le dōjō du château.",
      gameplay: "Faibles blessures, mais excellent étourdissement.",
      stats: stats(29, 82, 43, 13, 73, 91, { flesh: 0.62, armor: 0.72, spirit: 0.55 }),
      passive: passive("merciful-strike", "Frappe sans tranchant", "Les dégâts de posture augmentent de 30 %, mais les dégâts de chair diminuent.", "onDamage", "stunTradeoff", 1.3),
      unlock: unlock("dojo", "Défi d’initiation du dōjō", "dojo-initiation"),
      sprites: existingSprites("elite", "bokuto"),
    }),
    weapon({
      id: "hachiwari",
      name: "Hachiwari",
      subtitle: "Brise-casque",
      category: "shortBlade",
      family: "breaker",
      animationProfile: "blade",
      slots: ["secondary"],
      tags: ["contondant", "armure", "contre"],
      rarity: "uncommon",
      lore: "Un outil court forgé pour ouvrir les protections rigides.",
      gameplay: "Très efficace contre les casques et la posture blindée.",
      stats: stats(51, 75, 31, 18, 88, 84, { flesh: 0.74, armor: 1.32, spirit: 0.62 }),
      passive: passive("helmet-splitter", "Fissure de kabuto", "Les coups portés à une cible blindée ignorent 20 % de sa garde.", "onArmorHit", "armorIgnore", 0.2),
      unlock: unlock("boss", "Vaincre le Kabuto blanc", "giant-07-shiro-kabuto"),
      sprites: existingSprites("elite", "hachiwari"),
    }),
    weapon({
      id: "jitte",
      name: "Jitte",
      subtitle: "Insigne du magistrat",
      category: "shortBlade",
      family: "parryingTool",
      animationProfile: "blade",
      slots: ["secondary"],
      tags: ["contre", "désarmement", "non létal"],
      rarity: "uncommon",
      lore: "L’insigne martial d’un officier chargé d’arrêter les contrebandiers.",
      gameplay: "Coince les armes et facilite les contres.",
      stats: stats(28, 81, 29, 14, 68, 94, { flesh: 0.58, armor: 0.92, spirit: 0.5 }),
      passive: passive("weapon-catch", "Dent du magistrat", "Une parade parfaite désarme brièvement un ennemi ordinaire.", "onPerfectParry", "disarm", 1, 5),
      unlock: unlock("contract", "Contrat du magistrat disparu", "lost-magistrate"),
      sprites: existingSprites("elite", "jitte"),
    }),
    weapon({
      id: "kikuchi-yari",
      name: "Kikuchi-yari",
      subtitle: "Lance ancienne",
      category: "polearm",
      family: "spear",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["estoc", "précision", "point faible"],
      rarity: "rare",
      lore: "Une lance droite et étroite conservée parmi les armes anciennes du domaine.",
      gameplay: "Une pointe précise avec un fort bonus sur point faible.",
      stats: stats(64, 68, 87, 28, 61, 83, { flesh: 1.12, armor: 1.08, spirit: 0.7 }),
      passive: passive("needle-thrust", "Aiguille de Kikuchi", "Les touches au centre d’une cible infligent 25 % de dégâts supplémentaires.", "onWeakPointHit", "weakPointDamage", 1.25),
      unlock: unlock("secret", "Armurerie scellée du donjon", "castle-old-armory"),
      sprites: existingSprites("elite", "kikuchi-yari"),
    }),
    weapon({
      id: "naginata-lourde",
      name: "Naginata lourde",
      subtitle: "Gardienne de porte",
      category: "polearm",
      family: "naginata",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["tranchant", "balayage", "recul"],
      rarity: "rare",
      lore: "Une variante de garde aux ferrures épaisses, destinée à tenir une porte.",
      gameplay: "Balayage lent qui repousse fortement les groupes.",
      stats: stats(79, 35, 91, 49, 83, 55, { flesh: 1.15, armor: 1.04, spirit: 0.72, boss: 1.03 }),
      passive: passive("gatekeeper-sweep", "Mur de lames", "L’attaque lourde repousse toutes les cibles ordinaires touchées.", "onHeavyHit", "areaKnockback", 1.35, 2),
      unlock: unlock("boss", "Vaincre la Geôlière Sekimon", "boss-01-geoliere-sekimon"),
      sprites: existingSprites("elite", "naginata-lourde"),
    }),
    weapon({
      id: "odachi",
      name: "Ōdachi",
      subtitle: "Grande lame de campagne",
      category: "heavy",
      family: "greatBlade",
      animationProfile: "heavy",
      slots: ["primary"],
      tags: ["tranchant", "lourd", "zone"],
      rarity: "epic",
      lore: "Une très longue lame cérémonielle sortie lors du siège sanitaire.",
      gameplay: "Arc immense et engagement lent.",
      stats: stats(91, 24, 94, 63, 93, 39, { flesh: 1.25, armor: 1.22, spirit: 0.79, boss: 1.12 }),
      passive: passive("campaign-arc", "Arc de campagne", "Le troisième coup d’un combo frappe une cible supplémentaire.", "onComboFinisher", "extraTarget", 1),
      unlock: unlock("boss", "Vaincre le Cavalier Kurogoma", "boss-15-cavalier-kurogoma"),
      sprites: existingSprites("elite", "odachi"),
    }),
    weapon({
      id: "otsuchi",
      name: "Ōtsuchi",
      subtitle: "Maillet de siège",
      category: "heavy",
      family: "hammer",
      animationProfile: "heavy",
      slots: ["primary"],
      tags: ["contondant", "onde de choc", "destruction"],
      rarity: "rare",
      lore: "Un grand maillet employé pour réparer les portes avant de servir à les défendre.",
      gameplay: "Onde de choc courte et recul extrême.",
      stats: stats(94, 18, 58, 71, 100, 31, { flesh: 0.94, armor: 1.46, spirit: 0.58, boss: 1.18 }),
      passive: passive("earth-shock", "Marteau de terre", "Une attaque lourde au sol produit une onde de choc courte.", "onGroundHeavy", "shockwave", 0.85, 4),
      unlock: unlock("artisan", "Forgeron Kaji — chef-d’œuvre", "kaji-masterwork"),
      sprites: existingSprites("elite", "otsuchi"),
    }),
    weapon({
      id: "shakujo",
      name: "Shakujō",
      subtitle: "Bâton annelé",
      category: "staff",
      family: "ritualStaff",
      animationProfile: "staff",
      slots: ["primary"],
      tags: ["contondant", "son", "esprit"],
      rarity: "rare",
      lore: "Le bâton d’un moine itinérant disparu près des fosses.",
      gameplay: "Les anneaux perturbent les infectés sensibles au son.",
      stats: stats(47, 55, 79, 31, 68, 82, { flesh: 0.72, armor: 0.86, spirit: 1.38 }),
      passive: passive("ringing-ward", "Carillon de veille", "Chaque quatrième frappe étourdit les esprits proches.", "onHitStreak", "spiritStun", 0.8, 3),
      unlock: unlock("secret", "Tombe du moine sans nom", "nameless-monk"),
      sprites: existingSprites("elite", "shakujo"),
    }),
    weapon({
      id: "tachi",
      name: "Tachi",
      subtitle: "Lame de cavalier",
      category: "katana",
      family: "tachi",
      animationProfile: "blade",
      slots: ["primary"],
      tags: ["tranchant", "mobilité", "charge"],
      rarity: "rare",
      lore: "Une lame élégante portée par les cavaliers du domaine.",
      gameplay: "Les attaques lancées gagnent en puissance.",
      stats: stats(68, 70, 64, 31, 59, 76, { flesh: 1.13, armor: 0.98, spirit: 0.9 }),
      passive: passive("rider-cut", "Coupe du cavalier", "Attaquer après un sprint augmente les dégâts de 20 %.", "onSprintAttack", "sprintAttackDamage", 1.2),
      unlock: unlock("contract", "Contrat des écuries silencieuses", "silent-stables"),
      sprites: existingSprites("elite", "tachi"),
    }),
    weapon({
      id: "tanto",
      name: "Tantō",
      subtitle: "Poignard de dernier recours",
      category: "shortBlade",
      family: "dagger",
      animationProfile: "blade",
      slots: ["secondary"],
      tags: ["tranchant", "rapide", "exécution"],
      rarity: "uncommon",
      lore: "Une lame courte portée sous l’armure.",
      gameplay: "Très rapide, avec un fort multiplicateur sur point faible.",
      stats: stats(43, 96, 21, 9, 36, 91, { flesh: 1.18, armor: 0.54, spirit: 0.66 }),
      passive: passive("close-finish", "Sous la garde", "Les exécutions et points faibles infligent 35 % de dégâts supplémentaires.", "onWeakPointHit", "weakPointDamage", 1.35),
      unlock: unlock("chapter", "Trouvé dans la résidence du daimyō", 2),
      sprites: existingSprites("elite", "tanto"),
    }),
    weapon({
      id: "tessen-ferme",
      name: "Tessen renforcé",
      subtitle: "Éventail fermé",
      category: "fan",
      family: "warFan",
      animationProfile: "fan",
      slots: ["secondary"],
      tags: ["contre", "discret", "rapide"],
      rarity: "rare",
      lore: "Un éventail ferré conçu pour rester discret à la cour.",
      gameplay: "Parade compacte et contre très rapide.",
      stats: stats(34, 91, 24, 11, 66, 96, { flesh: 0.65, armor: 0.88, spirit: 0.82 }),
      passive: passive("hidden-iron", "Fer sous la soie", "Après une parade, le prochain contre ne consomme pas de Ki.", "onPerfectParry", "freeCounter", 1, 4),
      unlock: unlock("secret", "Cabinet du conseiller", "advisor-cabinet"),
      sprites: existingSprites("elite", "tessen-ferme"),
    }),
    weapon({
      id: "wakizashi",
      name: "Wakizashi",
      subtitle: "Compagnon des couloirs",
      category: "shortBlade",
      family: "shortSword",
      animationProfile: "blade",
      slots: ["secondary"],
      tags: ["tranchant", "rapide", "contre"],
      rarity: "common",
      lore: "Une lame courte adaptée aux pièces étroites et aux couloirs du donjon.",
      gameplay: "Portée réduite, excellente vitesse et contre fiable.",
      stats: stats(45, 88, 35, 14, 48, 88, { flesh: 1.05, armor: 0.75, spirit: 0.82 }),
      passive: passive("narrow-room", "Lame de corridor", "La cadence augmente de 10 % dans les intérieurs FPS.", "passive", "indoorAttackSpeed", 1.1),
      unlock: unlock("starter", "Équipement secondaire d’Akio"),
      unlockedByDefault: true,
      sprites: existingSprites("elite", "wakizashi"),
    }),

    weapon({
      id: "jumonji-yari",
      name: "Jūmonji-yari",
      subtitle: "Lance en croix",
      category: "polearm",
      family: "spear",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["estoc", "capture", "charge"],
      rarity: "rare",
      lore: "Ses lames latérales furent forgées pour retenir les assaillants aux portes.",
      gameplay: "Accroche et stoppe les charges.",
      stats: stats(68, 54, 91, 35, 74, 82, { flesh: 1.08, armor: 1.12, spirit: 0.68 }),
      passive: passive("cross-stop", "Croix d’arrêt", "Interrompt automatiquement une charge ennemie touchée de face.", "onChargeHit", "stopCharge", 1, 2),
      unlock: unlock("boss", "Vaincre le Capitaine Byakko", "mb-20-capitaine-byakko"),
      sprites: existingSprites("polearms", "jumonji-yari"),
    }),
    weapon({
      id: "kama-yari",
      name: "Kama-yari",
      subtitle: "Lance à crochet",
      category: "polearm",
      family: "hookSpear",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["estoc", "crochet", "armure"],
      rarity: "uncommon",
      lore: "Une lance employée pour désarçonner et ouvrir les armures.",
      gameplay: "Attire une cible légère et expose une garde.",
      stats: stats(62, 59, 88, 33, 71, 84, { flesh: 1, armor: 1.16, spirit: 0.65 }),
      passive: passive("hook-open", "Crochet d’ouverture", "Une attaque lourde attire les cibles légères.", "onHeavyHit", "pull", 0.7, 3),
      unlock: unlock("contract", "Contrat des portes barricadées", "barricaded-gates"),
      sprites: existingSprites("polearms", "kama-yari"),
    }),
    weapon({
      id: "kanabo",
      name: "Kanabō",
      subtitle: "Massue cloutée",
      category: "heavy",
      family: "club",
      animationProfile: "heavy",
      slots: ["primary"],
      tags: ["contondant", "étourdissement", "recul"],
      rarity: "uncommon",
      lore: "Une massue récupérée sur une brute au kabuto.",
      gameplay: "Étourdit et repousse au prix d’un fort coût de Ki.",
      stats: stats(84, 28, 57, 56, 94, 44, { flesh: 1.02, armor: 1.31, spirit: 0.52, boss: 1.08 }),
      passive: passive("iron-stars", "Étoiles de fer", "Les coups lourds appliquent davantage d’étourdissement.", "onHeavyHit", "stun", 1.4, 2),
      unlock: unlock("boss", "Vaincre la Brute au kabuto", "legacy-kabuto-brute"),
      sprites: existingSprites("polearms", "kanabo"),
    }),
    weapon({
      id: "masakari",
      name: "Masakari",
      subtitle: "Hache de guerre",
      category: "heavy",
      family: "axe",
      animationProfile: "heavy",
      slots: ["primary"],
      tags: ["tranchant", "armure", "destruction"],
      rarity: "rare",
      lore: "Une hache lourde de l’arsenal du daimyō.",
      gameplay: "Brise-garde lent, excellent contre l’armure et le bois.",
      stats: stats(88, 25, 52, 59, 91, 38, { flesh: 1.16, armor: 1.36, spirit: 0.55, boss: 1.1 }),
      passive: passive("cleave-wood", "Sentence du bûcheron", "Les éléments destructibles et les boucliers subissent deux fois plus de dégâts.", "onDamage", "destructibleDamage", 2),
      unlock: unlock("artisan", "Forgeron Kaji — plan de masakari", "kaji-masakari"),
      sprites: existingSprites("polearms", "masakari"),
    }),
    weapon({
      id: "nagamaki",
      name: "Nagamaki",
      subtitle: "Longue lame de ligne",
      category: "polearm",
      family: "nagamaki",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["tranchant", "portée", "ligne"],
      rarity: "rare",
      lore: "Une longue lame réservée aux suivants capables de rompre une ligne compacte.",
      gameplay: "Coups lourds à portée intermédiaire.",
      stats: stats(80, 38, 83, 46, 82, 58, { flesh: 1.17, armor: 1.08, spirit: 0.72, boss: 1.04 }),
      passive: passive("line-breaker", "Briseur de ligne", "Le premier ennemi touché ne bloque pas le balayage.", "onHit", "pierceTargets", 1),
      unlock: unlock("boss", "Vaincre la Générale Murasaki", "boss-12-generale-murasaki"),
      sprites: existingSprites("polearms", "nagamaki"),
    }),
    weapon({
      id: "naginata",
      name: "Naginata",
      subtitle: "Garde des sōhei",
      category: "polearm",
      family: "naginata",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["tranchant", "balayage", "défense"],
      rarity: "uncommon",
      lore: "L’arme de garde des sōhei avant leur contamination.",
      gameplay: "Grands balayages et défense sûre contre les groupes.",
      stats: stats(66, 57, 88, 34, 69, 81, { flesh: 1.12, armor: 0.94, spirit: 0.9 }),
      passive: passive("temple-circle", "Cercle du sanctuaire", "Toucher deux ennemis rend cinq points de Ki.", "onMultiHit", "restoreKi", 5, 2),
      unlock: unlock("chapter", "Sanctuaire du bambou brisé", 2),
      sprites: existingSprites("polearms", "naginata"),
    }),
    weapon({
      id: "ono",
      name: "Ono",
      subtitle: "Hache de quarantaine",
      category: "heavy",
      family: "axe",
      animationProfile: "heavy",
      slots: ["primary", "secondary"],
      tags: ["tranchant", "bois", "compact"],
      rarity: "common",
      lore: "Une hache de bûcheron réquisitionnée pour dresser les palissades.",
      gameplay: "Courte, robuste et efficace contre le bois.",
      stats: stats(64, 56, 38, 29, 72, 67, { flesh: 1.08, armor: 0.93, spirit: 0.58 }),
      passive: passive("quarantine-axe", "Outil de quarantaine", "Détruire un obstacle rend dix points de Ki.", "onDestructibleBreak", "restoreKi", 10, 1),
      unlock: unlock("chapter", "Camp des bûcherons de Kurokawa", 1),
      sprites: existingSprites("polearms", "ono"),
    }),
    weapon({
      id: "sasumata",
      name: "Sasumata",
      subtitle: "Fourche de capture",
      category: "polearm",
      family: "capturePole",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["capture", "contrôle", "non létal"],
      rarity: "uncommon",
      lore: "Un outil des postes de ville réemployé pour contenir les infectés.",
      gameplay: "Immobilise sans infliger de lourds dégâts.",
      stats: stats(24, 62, 94, 31, 45, 100, { flesh: 0.48, armor: 0.65, spirit: 0.45 }),
      passive: passive("forked-restraint", "Fourche d’arrêt", "Une attaque lourde immobilise une cible ordinaire pendant 1,2 seconde.", "onHeavyHit", "root", 1.2, 5),
      unlock: unlock("contract", "Sauver le poste de garde", "guard-post"),
      sprites: existingSprites("polearms", "sasumata"),
    }),
    weapon({
      id: "sodegarami",
      name: "Sodegarami",
      subtitle: "Enrouleur de manches",
      category: "polearm",
      family: "capturePole",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["capture", "désarmement", "crochet"],
      rarity: "uncommon",
      lore: "Ses crochets saisissaient autrefois les manches des suspects.",
      gameplay: "Arrache les protections légères et interrompt les attaques.",
      stats: stats(38, 52, 92, 36, 62, 95, { flesh: 0.72, armor: 1.07, spirit: 0.55 }),
      passive: passive("sleeve-tear", "Prise du geôlier", "Interrompre une attaque réduit la garde de la cible.", "onInterrupt", "guardBreak", 0.25, 3),
      unlock: unlock("chapter", "Ville-prison de Kurokawa", 6),
      sprites: existingSprites("polearms", "sodegarami"),
    }),
    weapon({
      id: "su-yari",
      name: "Su-yari",
      subtitle: "Lance droite",
      category: "polearm",
      family: "spear",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["estoc", "portée", "simple"],
      rarity: "common",
      lore: "La lance standard des barrages d’ashigaru autour de Kurokawa.",
      gameplay: "Estoc rapide, longue portée et faible arc vertical.",
      stats: stats(55, 72, 90, 24, 58, 86, { flesh: 1.08, armor: 0.98, spirit: 0.62 }),
      passive: passive("measured-thrust", "Mesure de l’ashigaru", "Les estocs à portée maximale infligent 18 % de dégâts supplémentaires.", "onMaxRangeHit", "damage", 1.18),
      unlock: unlock("chapter", "Barrage d’ashigaru de Kurokawa", 1),
      sprites: existingSprites("polearms", "su-yari"),
    }),
    weapon({
      id: "tetsubo",
      name: "Tetsubō",
      subtitle: "Barre de fer",
      category: "heavy",
      family: "club",
      animationProfile: "heavy",
      slots: ["primary"],
      tags: ["contondant", "armure", "très lourd"],
      rarity: "epic",
      lore: "Une barre de fer destinée aux gardes les plus massifs.",
      gameplay: "Extrêmement lente et redoutable contre les carapaces.",
      stats: stats(100, 12, 61, 78, 100, 22, { flesh: 1, armor: 1.58, spirit: 0.42, boss: 1.22 }),
      passive: passive("iron-verdict", "Verdict de fer", "Une attaque lourde pleinement chargée ne peut pas être bloquée.", "onChargedHeavy", "unblockable", 1, 4),
      unlock: unlock("boss", "Vaincre le Gardien au masque de fer", "mb-12-gardien-masque-fer"),
      sprites: existingSprites("polearms", "tetsubo"),
    }),
    weapon({
      id: "tsukubo",
      name: "Tsukubō",
      subtitle: "Perche de poussée",
      category: "polearm",
      family: "capturePole",
      animationProfile: "polearm",
      slots: ["primary"],
      tags: ["contrôle", "recul", "défense"],
      rarity: "common",
      lore: "Une perche conservée dans les maisons de garde de Kurokawa.",
      gameplay: "Repousse plusieurs ennemis et crée de l’espace.",
      stats: stats(31, 64, 89, 26, 52, 96, { flesh: 0.56, armor: 0.62, spirit: 0.48 }),
      passive: passive("clear-the-road", "Dégagez la voie", "Chaque cible supplémentaire augmente le recul du balayage.", "onMultiHit", "scalingKnockback", 0.18),
      unlock: unlock("chapter", "Maison de garde de Kurokawa", 1),
      sprites: existingSprites("polearms", "tsukubo"),
    }),

    weapon({
      id: "bajozutsu",
      name: "Bajōzutsu",
      subtitle: "Pistolet à mèche",
      category: "firearm",
      family: "matchlock",
      animationProfile: "firearm",
      slots: ["ranged"],
      tags: ["projectile", "feu", "recul"],
      rarity: "rare",
      lore: "Un petit pistolet à mèche réservé aux combats rapprochés.",
      gameplay: "Décharge puissante, recul fort et rechargement long.",
      stats: stats(86, 28, 57, 0, 87, 55, { flesh: 1.28, armor: 1.18, spirit: 0.42 }),
      passive: passive("corridor-shot", "Tonnerre de poche", "À moins de trois mètres, le tir inflige 30 % de dégâts supplémentaires.", "onCloseShot", "damage", 1.3),
      unlock: unlock("secret", "Coffre de l’arquebusier", "arquebusier-cache"),
      ammoType: "tamade",
      maxAmmo: 8,
      sprites: existingSprites("ranged", "bajozutsu"),
    }),
    weapon({
      id: "bo",
      name: "Bō",
      subtitle: "Bâton long",
      category: "staff",
      family: "staff",
      animationProfile: "staff",
      slots: ["primary"],
      tags: ["contondant", "combo", "défense"],
      rarity: "common",
      lore: "Le bâton des pèlerins qui tentaient d’atteindre le sanctuaire.",
      gameplay: "Enchaînements rapides, portée sûre et dégâts non tranchants.",
      stats: stats(42, 76, 82, 19, 64, 91, { flesh: 0.68, armor: 0.72, spirit: 0.9 }),
      passive: passive("pilgrim-rhythm", "Rythme du pèlerin", "Chaque frappe consécutive réduit le coût de Ki du combo.", "onComboHit", "comboKiDiscount", 0.08),
      unlock: unlock("chapter", "Route des pèlerins", 2),
      sprites: existingSprites("ranged", "bo"),
    }),
    weapon({
      id: "chigiriki",
      name: "Chigiriki",
      subtitle: "Fléau dissimulé",
      category: "flexible",
      family: "chainFlail",
      animationProfile: "flexible",
      slots: ["primary", "secondary"],
      tags: ["chaîne", "étourdissement", "imprévisible"],
      rarity: "rare",
      lore: "Un fléau compact caché parmi les bâtons des gardes en civil.",
      gameplay: "Frappe imprévisible avec un bon étourdissement.",
      stats: stats(61, 48, 68, 34, 82, 72, { flesh: 0.94, armor: 1.14, spirit: 0.61 }),
      passive: passive("hidden-flail", "Allonge trompeuse", "La première frappe après un changement d’arme gagne 25 % d’allonge.", "onWeaponSwapAttack", "reach", 1.25, 3),
      unlock: unlock("contract", "Contrat des gardes en civil", "plainclothes-guards"),
      renderMode: "segmented-chain",
      components: chainComponents("chigiriki", ["handle", "weight"]),
      sprites: existingSprites("ranged", "chigiriki"),
    }),
    weapon({
      id: "jo",
      name: "Jō",
      subtitle: "Bâton court",
      category: "staff",
      family: "staff",
      animationProfile: "staff",
      slots: ["primary", "secondary"],
      tags: ["contondant", "rapide", "parade"],
      rarity: "common",
      lore: "Le bâton court des patrouilles civiles de Kurokawa.",
      gameplay: "Parades faciles et coups rapides.",
      stats: stats(34, 88, 55, 14, 58, 95, { flesh: 0.62, armor: 0.68, spirit: 0.81 }),
      passive: passive("civil-watch", "Garde de quartier", "Bloquer une attaque réduit de moitié le coût du contre.", "onBlock", "counterKiCost", 0.5),
      unlock: unlock("chapter", "Patrouille civile de Kurokawa", 1),
      sprites: existingSprites("ranged", "jo"),
    }),
    weapon({
      id: "kusarigama",
      name: "Kusarigama",
      subtitle: "Faucille à chaîne",
      category: "flexible",
      family: "chainSickle",
      animationProfile: "flexible",
      slots: ["primary"],
      tags: ["chaîne", "tranchant", "capture"],
      rarity: "epic",
      lore: "La faucille à chaîne des éclaireurs des rizières infestées.",
      gameplay: "Alterne entaille courte et capture à moyenne portée.",
      stats: stats(59, 58, 83, 38, 61, 94, { flesh: 1.14, armor: 0.82, spirit: 0.86 }),
      passive: passive("harvest-chain", "Entrave du moissonneur", "L’attaque lourde ramène une cible légère à portée de faucille.", "onHeavyHit", "pull", 0.9, 4),
      unlock: unlock("boss", "Vaincre la Kunoichi Veuve", "mb-15-kunoichi-veuve"),
      renderMode: "segmented-chain",
      components: chainComponents("kusarigama", ["blade", "weight"]),
      sprites: existingSprites("ranged", "kusarigama"),
    }),
    weapon({
      id: "manrikigusari",
      name: "Manrikigusari",
      subtitle: "Chaîne aux dix mille forces",
      category: "flexible",
      family: "weightedChain",
      animationProfile: "flexible",
      slots: ["primary", "secondary"],
      tags: ["chaîne", "capture", "garde"],
      rarity: "rare",
      lore: "Une chaîne lestée portée discrètement par les agents du château.",
      gameplay: "Enroule une cible ou frappe autour d’une garde.",
      stats: stats(46, 66, 74, 26, 69, 100, { flesh: 0.82, armor: 0.94, spirit: 0.72 }),
      passive: passive("ten-thousand-grip", "Dix mille prises", "Toucher une cible en garde augmente les dégâts de posture de 35 %.", "onGuardHit", "postureDamage", 1.35),
      unlock: unlock("secret", "Cache des agents du château", "castle-agent-cache"),
      renderMode: "segmented-chain",
      components: chainComponents("manrikigusari", ["weightA", "weightB"]),
      sprites: existingSprites("ranged", "manrikigusari"),
    }),
    weapon({
      id: "tanegashima-cavalerie",
      name: "Tanegashima de cavalerie",
      subtitle: "Arquebuse raccourcie",
      category: "firearm",
      family: "matchlock",
      animationProfile: "firearm",
      slots: ["ranged"],
      tags: ["projectile", "feu", "mobile"],
      rarity: "rare",
      lore: "Une version raccourcie portée par les messagers armés du bakufu.",
      gameplay: "Moins précise mais utilisable en déplacement.",
      stats: stats(78, 42, 72, 0, 74, 61, { flesh: 1.22, armor: 1.1, spirit: 0.4 }),
      passive: passive("rider-volley", "Feu en mouvement", "Le tir en déplacement ne subit que la moitié de la pénalité de précision.", "passive", "movingAccuracy", 0.5),
      unlock: unlock("contract", "Convoi du bakufu", "bakufu-convoy"),
      ammoType: "tamade",
      maxAmmo: 10,
      sprites: existingSprites("ranged", "tanegashima-cavalerie"),
    }),
    weapon({
      id: "tanegashima-teppo",
      name: "Tanegashima teppō",
      subtitle: "Arquebuse longue",
      category: "firearm",
      family: "matchlock",
      animationProfile: "firearm",
      slots: ["ranged"],
      tags: ["projectile", "feu", "longue portée"],
      rarity: "epic",
      lore: "Une arquebuse à mèche stockée dans la tour de guet de Kurokawa.",
      gameplay: "Impact massif, fumée révélatrice et rechargement long.",
      stats: stats(96, 14, 100, 0, 92, 77, { flesh: 1.34, armor: 1.31, spirit: 0.38, boss: 1.15 }),
      passive: passive("watchtower-shot", "Tir de la tour", "Un tir immobile pendant une seconde gagne 20 % de dégâts.", "onAimedShot", "damage", 1.2),
      unlock: unlock("secret", "Tour de guet de Kurokawa", "kurokawa-watchtower"),
      ammoType: "tamade",
      maxAmmo: 6,
      sprites: existingSprites("ranged", "tanegashima-teppo"),
    }),
    weapon({
      id: "tessen-ouvert",
      name: "Tessen ouvert",
      subtitle: "Éventail de guerre",
      category: "fan",
      family: "warFan",
      animationProfile: "fan",
      slots: ["secondary"],
      tags: ["contre", "projectile", "balayage"],
      rarity: "rare",
      lore: "L’éventail de guerre d’un officier qui commandait sans dégainer.",
      gameplay: "Pare les projectiles et produit un court balayage.",
      stats: stats(31, 77, 36, 16, 59, 98, { flesh: 0.62, armor: 0.71, spirit: 1.04 }),
      passive: passive("iron-gust", "Vent de fer", "Une parade parfaite renvoie les projectiles légers.", "onProjectileParry", "reflectProjectile", 1, 2),
      unlock: unlock("boss", "Vaincre le Courtisan au tessen", "s07-tessen-courtier"),
      sprites: existingSprites("ranged", "tessen-ouvert"),
    }),
    weapon({
      id: "uchine",
      name: "Uchine",
      subtitle: "Trait à corde",
      category: "throwing",
      family: "throwingDart",
      animationProfile: "throwing",
      slots: ["ranged"],
      tags: ["projectile", "récupérable", "interruption"],
      rarity: "uncommon",
      lore: "Un trait court d’urgence conservé à la ceinture des archers.",
      gameplay: "Projectile récupérable qui interrompt les petites cibles.",
      stats: stats(52, 71, 69, 0, 44, 78, { flesh: 1.03, armor: 0.7, spirit: 0.62 }),
      passive: passive("retrievable-dart", "Corde de rappel", "Une uchine manquée peut être récupérée à courte distance.", "onProjectileMiss", "recoverAmmo", 1),
      unlock: unlock("chapter", "Camp des archers de Sekisho", 3),
      ammoType: "uchine",
      maxAmmo: 5,
      sprites: existingSprites("ranged", "uchine"),
    }),
    weapon({
      id: "yumi-daikyu",
      name: "Yumi daikyū",
      subtitle: "Grand arc asymétrique",
      category: "bow",
      family: "bow",
      animationProfile: "bow",
      slots: ["ranged"],
      tags: ["projectile", "charge", "longue portée"],
      rarity: "rare",
      lore: "Le grand arc d’un archer au service direct du daimyō.",
      gameplay: "Tir chargé puissant, lent et précis.",
      stats: stats(84, 29, 100, 22, 72, 92, { flesh: 1.24, armor: 0.91, spirit: 0.68, boss: 1.05 }),
      passive: passive("full-draw", "Pleine allonge", "Un tir totalement chargé traverse une cible ordinaire.", "onChargedShot", "pierceTargets", 1),
      unlock: unlock("boss", "Vaincre l’Archer d’os", "mb-08-archer-os"),
      ammoType: "ya",
      maxAmmo: 20,
      sprites: existingSprites("ranged", "yumi-daikyu"),
    }),
    weapon({
      id: "yumi-hankyu",
      name: "Yumi hankyū",
      subtitle: "Arc court de chasse",
      category: "bow",
      family: "bow",
      animationProfile: "bow",
      slots: ["ranged"],
      tags: ["projectile", "rapide", "mobile"],
      rarity: "uncommon",
      lore: "L’arc court des chasseurs de la bambouseraie.",
      gameplay: "Tirs rapides et bonne mobilité.",
      stats: stats(57, 76, 76, 13, 45, 86, { flesh: 1.08, armor: 0.69, spirit: 0.7 }),
      passive: passive("hunter-step", "Pas du chasseur", "Après un tir, la vitesse de déplacement augmente brièvement.", "onShot", "moveSpeed", 1.12, 2),
      unlock: unlock("chapter", "Bambouseraie des chasseurs", 2),
      ammoType: "ya",
      maxAmmo: 28,
      sprites: existingSprites("ranged", "yumi-hankyu"),
    }),

    weapon({
      id: "kunai",
      name: "Kunai",
      subtitle: "Lame-outil de shinobi",
      category: "throwing",
      family: "throwingKnife",
      animationProfile: "throwing",
      slots: ["secondary", "ranged"],
      tags: ["projectile", "rapide", "récupérable"],
      rarity: "common",
      lore: "Un outil de terrassement détourné par les éclaireurs pour le combat rapproché et le lancer.",
      gameplay: "Projectile rapide, précis et récupérable.",
      stats: stats(42, 91, 61, 0, 31, 93, { flesh: 1.12, armor: 0.54, spirit: 0.58 }),
      passive: passive("field-tool", "Outil de l’éclaireur", "Un kunai qui tue une cible ordinaire est automatiquement récupéré.", "onProjectileKill", "recoverAmmo", 1),
      unlock: unlock("starter", "Trousse d’éclaireur d’Akio"),
      unlockedByDefault: true,
      ammoType: "kunai",
      maxAmmo: 8,
      sprites: shinobiSprites("kunai"),
    }),
    weapon({
      id: "hira-shuriken",
      name: "Hira-shuriken",
      subtitle: "Lame plate en étoile",
      category: "throwing",
      family: "shuriken",
      animationProfile: "throwing",
      slots: ["ranged"],
      tags: ["projectile", "rapide", "multi-cible"],
      rarity: "uncommon",
      lore: "Une lame plate forgée pour distraire, blesser et briser le rythme d’une poursuite.",
      gameplay: "Lancer très rapide, dégâts modestes et ricochet léger.",
      stats: stats(31, 100, 58, 0, 26, 88, { flesh: 0.92, armor: 0.4, spirit: 0.52 }),
      passive: passive("four-points", "Quatre pointes", "Une touche critique ricoche vers une cible proche.", "onCriticalProjectile", "ricochet", 1, 2),
      unlock: unlock("contract", "Contrat des toits de Kurokawa", "kurokawa-rooftops"),
      ammoType: "shuriken",
      maxAmmo: 16,
      sprites: shinobiSprites("hira-shuriken"),
    }),
    weapon({
      id: "bo-shuriken",
      name: "Bō-shuriken",
      subtitle: "Pointe de lancer",
      category: "throwing",
      family: "shuriken",
      animationProfile: "throwing",
      slots: ["ranged"],
      tags: ["projectile", "précision", "point faible"],
      rarity: "uncommon",
      lore: "Une pointe droite et discrète, équilibrée pour une trajectoire tendue.",
      gameplay: "Plus lente qu’une étoile, mais précise et perforante.",
      stats: stats(48, 82, 71, 0, 38, 97, { flesh: 1.1, armor: 0.73, spirit: 0.5 }),
      passive: passive("straight-flight", "Vol sans détour", "Les points faibles subissent 30 % de dégâts supplémentaires.", "onWeakPointHit", "weakPointDamage", 1.3),
      unlock: unlock("dojo", "Défi de précision du dōjō", "dojo-precision"),
      ammoType: "boShuriken",
      maxAmmo: 12,
      sprites: shinobiSprites("bo-shuriken"),
    }),
    weapon({
      id: "makibishi",
      name: "Makibishi",
      subtitle: "Chausses-trappes",
      category: "throwing",
      family: "trap",
      animationProfile: "throwing",
      slots: ["ranged"],
      tags: ["piège", "contrôle", "zone"],
      rarity: "uncommon",
      lore: "De petites pointes répandues sur une voie de fuite pour ralentir les poursuivants.",
      gameplay: "Crée au sol une zone qui ralentit et blesse les ennemis légers.",
      stats: stats(22, 65, 44, 0, 34, 100, { flesh: 0.73, armor: 0.25, spirit: 0.2 }),
      passive: passive("barbed-road", "Route hérissée", "Les ennemis ralentis subissent 15 % de dégâts de posture supplémentaires.", "onTrapHit", "postureVulnerability", 1.15),
      unlock: unlock("contract", "Contrat de la route de Sekisho", "sekisho-road"),
      ammoType: "makibishi",
      maxAmmo: 5,
      sprites: shinobiSprites("makibishi"),
    }),
    weapon({
      id: "kyoketsu-shoge",
      name: "Kyoketsu-shōge",
      subtitle: "Dague à corde et anneau",
      category: "flexible",
      family: "ropeDart",
      animationProfile: "flexible",
      slots: ["primary", "secondary"],
      tags: ["chaîne", "crochet", "mobilité"],
      rarity: "epic",
      lore: "Une dague à crochet reliée à un anneau, utilisée pour saisir une prise ou une cible.",
      gameplay: "Contrôle à longue portée et repositionnement rapide.",
      stats: stats(52, 67, 96, 37, 54, 100, { flesh: 1.08, armor: 0.66, spirit: 0.83 }),
      passive: passive("empty-ring", "Anneau du vide", "Une attaque lourde réussie attire Akio vers une cible massive.", "onHeavyHit", "grappleToTarget", 0.8, 4),
      unlock: unlock("boss", "Vaincre le Maître shinobi Kumo", "boss-14-maitre-shinobi-kumo"),
      renderMode: "segmented-chain",
      components: chainComponents("kyoketsu-shoge", ["blade", "ring"]),
      sprites: shinobiSprites("kyoketsu-shoge", true),
    }),
    weapon({
      id: "kusari-kunai",
      name: "Kusari-kunai",
      subtitle: "Kunai à chaîne",
      category: "flexible",
      family: "chainDart",
      animationProfile: "flexible",
      slots: ["primary", "secondary"],
      tags: ["chaîne", "projectile", "capture"],
      rarity: "rare",
      lore: "Un kunai renforcé relié à une chaîne courte, conçu pour frapper puis revenir à la main.",
      gameplay: "Lancer captif, traction légère et attaque circulaire.",
      stats: stats(55, 72, 82, 29, 49, 96, { flesh: 1.1, armor: 0.74, spirit: 0.69 }),
      passive: passive("returning-fang", "Croc de retour", "Le retour de la chaîne peut toucher une seconde fois.", "onChainReturn", "returnHit", 0.55, 1),
      unlock: unlock("contract", "Contrat de l’espion de Kurokawa", "kurokawa-spy"),
      renderMode: "segmented-chain",
      components: chainComponents("kusari-kunai", ["kunai", "weight"]),
      sprites: shinobiSprites("kusari-kunai", true),
    }),
    weapon({
      id: "nunchaku-ryukyu",
      name: "Nunchaku de Ryūkyū",
      subtitle: "Arme rare des îles du Sud",
      category: "flexible",
      family: "nunchaku",
      animationProfile: "flexible",
      slots: ["primary", "secondary"],
      tags: ["chaîne", "combo", "étourdissement"],
      rarity: "epic",
      lore: "Une arme rare arrivée du royaume de Ryūkyū par les routes marchandes de Satsuma.",
      gameplay: "Combos très rapides et étourdissement croissant, avec une faible allonge.",
      stats: stats(47, 100, 39, 18, 78, 89, { flesh: 0.82, armor: 0.91, spirit: 0.58 }),
      passive: passive("southern-rhythm", "Rythme des îles", "Chaque coup du même combo augmente l’étourdissement de 12 %.", "onComboHit", "stackingStun", 0.12),
      unlock: unlock("contract", "Convoi marchand de Satsuma", "satsuma-convoy"),
      renderMode: "segmented-chain",
      components: chainComponents("nunchaku-ryukyu", ["handleA", "handleB"]),
      sprites: shinobiSprites("nunchaku-ryukyu", true),
    }),
  ];

  const weaponMap = new Map(weapons.map((entry) => [entry.id, entry]));
  const defaultLoadout = Object.freeze({
    primary: "01-kurokage",
    secondary: "wakizashi",
    ranged: "kunai",
  });
  const defaultUnlockedWeapons = Object.freeze(
    // La chronique commence avec un équipement lisible. Les autres armes
    // restent visibles au dōjō, puis se débloquent par boss, chapitre,
    // contrat, secret ou artisan selon leur provenance de lore.
    weapons
      .filter((entry) => entry.playable && entry.unlockedByDefault)
      .map((entry) => entry.id),
  );

  function weaponById(id) {
    return weaponMap.get(String(id || "")) || null;
  }

  function isWeaponCompatibleWithSlot(weaponId, slotId) {
    const entry = weaponById(weaponId);
    return Boolean(entry && entry.playable && entry.slots.includes(String(slotId)));
  }

  function normalizeLoadout(loadout = {}) {
    const normalized = {};
    for (const slot of SLOT_DEFINITIONS) {
      const requested = loadout?.[slot.id];
      normalized[slot.id] = isWeaponCompatibleWithSlot(requested, slot.id)
        ? String(requested)
        : defaultLoadout[slot.id];
    }
    return normalized;
  }

  function weaponsForSlot(slotId) {
    return weapons.filter((entry) => entry.playable && entry.slots.includes(String(slotId)));
  }

  const defaults = Object.freeze({
    loadout: defaultLoadout,
    unlockedWeapons: defaultUnlockedWeapons,
  });

  global.KageArsenal = Object.freeze({
    schema: 1,
    weapons: Object.freeze(weapons),
    slots: SLOT_DEFINITIONS,
    categories: CATEGORY_DEFINITIONS,
    stats: STAT_DEFINITIONS,
    rarityLabels: RARITY_LABELS,
    defaults,
    defaultLoadout,
    defaultUnlockedWeapons,
    weaponById,
    weaponsForSlot,
    isWeaponCompatibleWithSlot,
    normalizeLoadout,
  });
})(window);
