(() => {
  "use strict";

  /*
   * Source de vérité spatiale de Yomi no Kage.
   *
   * Le moteur peut cloner les objets ci-dessous pour créer son état mutable,
   * mais ne doit plus reconstruire la géographie depuis des tableaux séparés.
   * Les coordonnées historiques importantes du prototype sont conservées :
   * départ x=56, torii x=900, retour du premier FPS x=1045 et donjon x=2190.
   */

  const HORIZONTAL_GROUND_Y = 300;
  const PLAYER_GROUND_Y = 273;

  const KageLevels = {
    schema: 1,
    campaignId: "yomi-no-kage",
    startAreaId: "kurokawa-main-street",
    startSpawnId: "prologue",
    designRules: {
      outdoorRequiredRoute: "horizontal",
      outdoorPlatformRole: "optionalUpper",
      structuralVerticalityZones: ["building", "castle"],
      portalInteraction: "manual",
      portalKey: "E",
      transitionSwapRatio: 0.5,
      persistentAreaState: true,
    },
    legacyCompatibility: {
      sideWidth: 2500,
      chapter0StartX: 56,
      chapter0FpsEntranceX: 900,
      chapter1ReturnX: 1045,
      chapter1FpsEntranceX: 2190,
      chapter1DoorBlockX: 2148,
      groundY: HORIZONTAL_GROUND_Y,
    },
    chapters: {
      village: {
        id: "village",
        label: "Kurokawa — village des cendres",
        areaIds: [
          "kurokawa-main-street",
          "kurokawa-back-street",
          "kurokawa-market-east",
        ],
        entryAreaId: "kurokawa-main-street",
        objectiveAreaId: "kurokawa-market-east",
      },
      castle: {
        id: "castle",
        label: "Donjon de Kurokawa",
        areaIds: [
          "castle-lower-court",
          "castle-residence",
          "castle-donjon",
        ],
        entryAreaId: "castle-lower-court",
        objectiveAreaId: "castle-donjon",
      },
    },
    mapGraph: {
      nodes: [
        { id: "kurokawa-main-street", mapX: 0, mapY: 0, kind: "outdoor" },
        { id: "kurokawa-back-street", mapX: 0, mapY: 1, kind: "outdoor" },
        { id: "kurokawa-market-east", mapX: 1, mapY: 0, kind: "outdoor" },
        { id: "castle-lower-court", mapX: 2, mapY: 0, kind: "castle" },
        { id: "castle-residence", mapX: 2, mapY: 1, kind: "building" },
        { id: "castle-donjon", mapX: 3, mapY: 0, kind: "castle" },
      ],
      edges: [
        {
          id: "main-back-alley",
          from: "kurokawa-main-street",
          to: "kurokawa-back-street",
          kind: "side",
          bidirectional: true,
        },
        {
          id: "main-market-gate",
          from: "kurokawa-main-street",
          to: "kurokawa-market-east",
          kind: "side",
          bidirectional: true,
        },
        {
          id: "back-market-passage",
          from: "kurokawa-back-street",
          to: "kurokawa-market-east",
          kind: "side",
          bidirectional: true,
        },
        {
          id: "market-castle-road",
          from: "kurokawa-market-east",
          to: "castle-lower-court",
          kind: "side",
          bidirectional: true,
          initiallyLocked: true,
          unlockEncounterId: "aka-ushi-east-gate",
        },
        {
          id: "court-residence-door",
          from: "castle-lower-court",
          to: "castle-residence",
          kind: "side",
          bidirectional: true,
        },
        {
          id: "residence-donjon-corridor",
          from: "castle-residence",
          to: "castle-donjon",
          kind: "side",
          bidirectional: true,
        },
      ],
    },
    areas: {
      "kurokawa-main-street": {
        id: "kurokawa-main-street",
        chapterId: "village",
        label: "Grande rue de Kurokawa",
        zoneKind: "outdoor",
        environmentIndex: 0,
        width: 2500,
        minX: 6,
        maxX: 2479,
        cameraMinX: 0,
        routeMetrics: {
          mainRoute: "horizontal",
          mainRouteLength: 2420,
          requiredClimb: 0,
          optionalUpperRoutes: 4,
        },
        spawns: {
          prologue: { x: 56, y: PLAYER_GROUND_Y, facing: 1 },
          fpsReturn: { x: 852, y: PLAYER_GROUND_Y, facing: 1 },
          backStreetReturn: { x: 1420, y: PLAYER_GROUND_Y, facing: -1 },
          marketReturn: { x: 2040, y: PLAYER_GROUND_Y, facing: -1 },
        },
        groundSegments: [
          {
            id: "main-earth-road",
            x: 0,
            y: HORIZONTAL_GROUND_Y,
            w: 2500,
            h: 60,
            collision: "solid",
            surface: "earth",
            routeRole: "main",
          },
        ],
        platforms: [
          {
            id: "burned-house-roof",
            x: 49,
            y: 254,
            w: 158,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "minka-chaume-brulee",
            surface: "thatch",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "west-watch-balcony",
            x: 318,
            y: 238,
            w: 64,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "tour-guet-ouest",
            surface: "wood",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "intact-house-awning",
            x: 541,
            y: 239,
            w: 164,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "minka-tuiles-intacte",
            surface: "roofTile",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "rice-storehouse-roof",
            x: 1072,
            y: 190,
            w: 126,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "kura-entrepot-riz",
            surface: "roofTile",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "broken-cart-shortcut",
            x: 1013,
            y: 270,
            w: 52,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "charrette-cassee",
            surface: "wood",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "haystack-shortcut",
            x: 1385,
            y: 258,
            w: 48,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "tas-paille",
            surface: "thatch",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
        ],
        props: [
          { id: "burned-minka-west", file: "minka-chaume-brulee", x: 42, width: 175, layer: "back" },
          { id: "village-barrier-west", file: "barriere-village", x: 220, width: 68, layer: "world" },
          { id: "watchtower-west", file: "tour-guet-kurokawa", x: 305, width: 82, layer: "back" },
          { id: "barrel-access", file: "tonneau-provisions", x: 500, width: 36, layer: "world" },
          { id: "intact-minka", file: "minka-tuiles-intacte", x: 535, width: 175, layer: "back" },
          { id: "street-fire", file: "foyer-incendie", x: 760, width: 54, layer: "back", bottomY: 294 },
          { id: "broken-cart", file: "charrette-cassee", x: 990, width: 78, layer: "world" },
          { id: "rice-storehouse", file: "kura-entrepot-riz", x: 1060, width: 150, layer: "back" },
          { id: "hay-access", file: "tas-paille", x: 1374, width: 70, layer: "world" },
          { id: "main-well", file: "puits-pierre", x: 1570, width: 48, layer: "back", bottomY: 294 },
          { id: "burned-quarter-barrel", file: "tonneau-provisions", x: 1770, width: 36, layer: "world" },
          { id: "burned-minka-east", file: "minka-chaume-brulee", x: 1810, width: 175, layer: "back" },
          { id: "road-altar", file: "autel-route", x: 2040, width: 48, layer: "back", bottomY: 294 },
          { id: "watchtower-east", file: "tour-guet-kurokawa", x: 2250, width: 82, layer: "back" },
        ],
        portals: [
          {
            id: "contaminated-torii",
            linkId: "sanctuary-fps",
            x: 900,
            approachX: 852,
            interactionRange: 58,
            collision: "passThrough",
            type: "fps",
            mission: 0,
            destination: { missionId: "contaminated-sanctuary" },
            returnDestination: {
              areaId: "kurokawa-main-street",
              spawnId: "fpsReturn",
            },
            state: "open",
            label: "Sanctuaire contaminé",
            prompt: "E — FRANCHIR LE TORII",
            persistentEncounterId: "sanctuary-seal",
          },
          {
            id: "alley-to-back-street",
            linkId: "main-back-alley",
            x: 1465,
            interactionRange: 48,
            collision: "portal",
            type: "side",
            destination: {
              areaId: "kurokawa-back-street",
              spawnId: "mainStreetReturn",
            },
            state: "open",
            visual: "passage-ruelle",
            label: "Ruelle derrière les maisons",
            prompt: "E — EMPRUNTER LA RUELLE",
          },
          {
            id: "gate-to-market",
            linkId: "main-market-gate",
            x: 2130,
            interactionRange: 52,
            collision: "portal",
            type: "side",
            destination: {
              areaId: "kurokawa-market-east",
              spawnId: "mainStreetReturn",
            },
            state: "open",
            visual: "porte-palissade",
            label: "Marché oriental",
            prompt: "E — PASSER LA PALISSADE",
          },
        ],
        enemies: [
          { id: "main-regular-01", roster: "regular", x: 296, y: 276, facing: -1 },
          { id: "main-regular-02", roster: "regular", x: 430, y: 276, facing: -1 },
          { id: "main-special-01", roster: "special", x: 735, y: 276, facing: -1 },
          { id: "main-regular-03", roster: "regular", x: 1260, y: 276, facing: -1 },
          { id: "main-regular-04", roster: "regular", x: 1680, y: 276, facing: -1 },
          { id: "main-special-02", roster: "special", x: 2430, y: 276, facing: -1 },
        ],
        pickups: [
          { id: "main-ofuda-west", x: 600, y: 266, kind: "ammo", amount: 4 },
          { id: "main-yomogi", x: 1280, y: 266, kind: "health", amount: 28 },
          { id: "main-ofuda-east", x: 1850, y: 266, kind: "ammo", amount: 4 },
        ],
        encounters: [],
      },

      "kurokawa-back-street": {
        id: "kurokawa-back-street",
        chapterId: "village",
        label: "Ruelle des puits",
        zoneKind: "outdoor",
        environmentIndex: 0,
        width: 2500,
        minX: 6,
        maxX: 2479,
        cameraMinX: 0,
        routeMetrics: {
          mainRoute: "horizontal",
          mainRouteLength: 2360,
          requiredClimb: 0,
          optionalUpperRoutes: 3,
        },
        spawns: {
          mainStreetReturn: { x: 150, y: PLAYER_GROUND_Y, facing: 1 },
          marketReturn: { x: 2290, y: PLAYER_GROUND_Y, facing: -1 },
          sickHouseReturn: { x: 1120, y: PLAYER_GROUND_Y, facing: 1 },
        },
        groundSegments: [
          {
            id: "back-street-earth",
            x: 0,
            y: HORIZONTAL_GROUND_Y,
            w: 2500,
            h: 60,
            collision: "solid",
            surface: "earth",
            routeRole: "main",
          },
        ],
        platforms: [
          {
            id: "back-cart",
            x: 460,
            y: 270,
            w: 64,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "charrette-cassee",
            surface: "wood",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "back-minka-roof",
            x: 820,
            y: 230,
            w: 150,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "minka-chaume-brulee",
            surface: "thatch",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "back-kura-awning",
            x: 1680,
            y: 242,
            w: 138,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "kura-entrepot-riz",
            surface: "roofTile",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
        ],
        props: [
          { id: "back-minka-01", file: "minka-chaume-brulee", x: 260, width: 175, layer: "back" },
          { id: "back-cart-01", file: "charrette-cassee", x: 450, width: 82, layer: "world" },
          { id: "back-well", file: "puits-pierre", x: 630, width: 48, layer: "back", bottomY: 294 },
          { id: "back-minka-02", file: "minka-chaume-brulee", x: 810, width: 175, layer: "back" },
          { id: "back-hay", file: "tas-paille", x: 1240, width: 74, layer: "world" },
          { id: "back-kura", file: "kura-entrepot-riz", x: 1660, width: 165, layer: "back" },
          { id: "back-fire", file: "foyer-incendie", x: 2010, width: 50, layer: "back", bottomY: 294 },
          { id: "back-barrier", file: "barriere-village", x: 2180, width: 74, layer: "world" },
        ],
        portals: [
          {
            id: "return-to-main-alley",
            linkId: "main-back-alley",
            x: 120,
            interactionRange: 48,
            collision: "portal",
            type: "return",
            destination: {
              areaId: "kurokawa-main-street",
              spawnId: "backStreetReturn",
            },
            state: "open",
            visual: "passage-ruelle",
            label: "Grande rue",
            prompt: "E — REVENIR À LA GRANDE RUE",
          },
          {
            id: "sick-house-fps",
            linkId: "sick-house-fps",
            x: 1160,
            interactionRange: 44,
            collision: "solidDoor",
            type: "fps",
            mission: "kurokawa-sick-house",
            destination: { missionId: "kurokawa-sick-house" },
            returnDestination: {
              areaId: "kurokawa-back-street",
              spawnId: "sickHouseReturn",
            },
            state: "closed",
            visual: "porte-minka",
            label: "Maison des malades",
            prompt: "E — OUVRIR LA PORTE",
            optional: true,
            persistentEncounterId: "sick-house-secret",
          },
          {
            id: "passage-to-market",
            linkId: "back-market-passage",
            x: 2350,
            interactionRange: 50,
            collision: "portal",
            type: "side",
            destination: {
              areaId: "kurokawa-market-east",
              spawnId: "backStreetReturn",
            },
            state: "open",
            visual: "passage-ruelle",
            label: "Arrière du marché",
            prompt: "E — SUIVRE LE PASSAGE",
          },
        ],
        enemies: [
          { id: "back-regular-01", roster: "regular", x: 360, y: 276, facing: -1 },
          { id: "back-regular-02", roster: "regular", x: 720, y: 276, facing: -1 },
          { id: "back-special-01", roster: "special", x: 1040, y: 276, facing: -1 },
          { id: "back-regular-03", roster: "regular", x: 1450, y: 276, facing: -1 },
          { id: "back-special-02", roster: "special", x: 1910, y: 276, facing: -1 },
          { id: "back-regular-04", roster: "regular", x: 2170, y: 276, facing: -1 },
        ],
        pickups: [
          { id: "back-yomogi", x: 650, y: 266, kind: "health", amount: 28 },
          { id: "back-cinder", x: 1310, y: 266, kind: "yomiAsh", amount: 1 },
          { id: "back-ofuda", x: 2050, y: 266, kind: "ammo", amount: 4 },
        ],
        encounters: [],
      },

      "kurokawa-market-east": {
        id: "kurokawa-market-east",
        chapterId: "village",
        label: "Marché oriental",
        zoneKind: "outdoor",
        environmentIndex: 0,
        width: 2500,
        minX: 6,
        maxX: 2479,
        cameraMinX: 0,
        routeMetrics: {
          mainRoute: "horizontal",
          mainRouteLength: 2320,
          requiredClimb: 0,
          optionalUpperRoutes: 2,
        },
        spawns: {
          mainStreetReturn: { x: 150, y: PLAYER_GROUND_Y, facing: 1 },
          backStreetReturn: { x: 720, y: PLAYER_GROUND_Y, facing: 1 },
          shrineReturn: { x: 820, y: PLAYER_GROUND_Y, facing: 1 },
          castleReturn: { x: 2330, y: PLAYER_GROUND_Y, facing: -1 },
          bossCheckpoint: { x: 1080, y: PLAYER_GROUND_Y, facing: 1 },
        },
        groundSegments: [
          {
            id: "market-earth",
            x: 0,
            y: HORIZONTAL_GROUND_Y,
            w: 2500,
            h: 60,
            collision: "solid",
            surface: "earth",
            routeRole: "main",
          },
        ],
        platforms: [
          {
            id: "market-cart-shortcut",
            x: 390,
            y: 270,
            w: 70,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "charrette-cassee",
            surface: "wood",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
          {
            id: "market-house-secret",
            x: 610,
            y: 226,
            w: 154,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "minka-tuiles-intacte",
            surface: "roofTile",
            collision: "oneWay",
            routeRole: "optionalUpper",
          },
        ],
        props: [
          { id: "market-cart", file: "charrette-cassee", x: 380, width: 84, layer: "world" },
          { id: "market-house", file: "minka-tuiles-intacte", x: 600, width: 175, layer: "back" },
          { id: "market-shrine", file: "autel-route", x: 815, width: 54, layer: "back", bottomY: 294 },
          { id: "market-well", file: "puits-pierre", x: 970, width: 48, layer: "back", bottomY: 294 },
          { id: "arena-barrier-west", file: "barriere-village", x: 1160, width: 76, layer: "world", destructible: true },
          { id: "arena-hay", file: "tas-paille", x: 1480, width: 76, layer: "world", destructible: true },
          { id: "arena-cart", file: "charrette-cassee", x: 1850, width: 88, layer: "world", destructible: true },
          { id: "arena-barrier-east", file: "barriere-village", x: 2110, width: 76, layer: "world", destructible: true },
          { id: "castle-road-watch", file: "tour-guet-kurokawa", x: 2260, width: 88, layer: "back" },
        ],
        portals: [
          {
            id: "return-to-main-gate",
            linkId: "main-market-gate",
            x: 120,
            interactionRange: 50,
            collision: "portal",
            type: "return",
            destination: {
              areaId: "kurokawa-main-street",
              spawnId: "marketReturn",
            },
            state: "open",
            visual: "porte-palissade",
            label: "Grande rue",
            prompt: "E — REVENIR À LA GRANDE RUE",
          },
          {
            id: "return-to-back-passage",
            linkId: "back-market-passage",
            x: 760,
            interactionRange: 48,
            collision: "portal",
            type: "return",
            destination: {
              areaId: "kurokawa-back-street",
              spawnId: "marketReturn",
            },
            state: "open",
            visual: "passage-ruelle",
            label: "Ruelle des puits",
            prompt: "E — PASSER DERRIÈRE LES MAISONS",
          },
          {
            id: "market-shrine-fps",
            linkId: "market-shrine-fps",
            x: 835,
            interactionRange: 44,
            collision: "solidDoor",
            type: "fps",
            mission: "market-road-shrine",
            destination: { missionId: "market-road-shrine" },
            returnDestination: {
              areaId: "kurokawa-market-east",
              spawnId: "shrineReturn",
            },
            state: "closed",
            visual: "porte-sanctuaire",
            label: "Chapelle de route",
            prompt: "E — OUVRIR LA CHAPELLE",
            optional: true,
            persistentEncounterId: "market-shrine-secret",
          },
          {
            id: "road-to-castle",
            linkId: "market-castle-road",
            x: 2380,
            interactionRange: 58,
            collision: "solidDoor",
            type: "side",
            destination: {
              areaId: "castle-lower-court",
              spawnId: "villageReturn",
            },
            state: "locked",
            unlockEncounterId: "aka-ushi-east-gate",
            visual: "porte-chateau",
            label: "Route du château",
            prompt: "E — OUVRIR LE PASSAGE",
          },
        ],
        enemies: [
          { id: "market-regular-01", roster: "regular", x: 280, y: 276, facing: -1 },
          { id: "market-special-01", roster: "special", x: 520, y: 276, facing: -1 },
          { id: "market-regular-02", roster: "regular", x: 980, y: 276, facing: -1 },
          {
            id: "aka-ushi",
            rosterId: "giant-02-aka-ushi",
            profileId: "giant-02-aka-ushi",
            presentationClass: "massive",
            encounterId: "aka-ushi-east-gate",
            x: 1880,
            y: 218,
            w: 128,
            h: 82,
            hp: 42,
            facing: -1,
            boss: true,
          },
        ],
        pickups: [
          { id: "market-checkpoint-yomogi", x: 1080, y: 266, kind: "health", amount: 28 },
          { id: "market-ofuda", x: 2220, y: 266, kind: "ammo", amount: 4 },
        ],
        checkpoints: [
          {
            id: "market-before-aka-ushi",
            x: 1080,
            spawnId: "bossCheckpoint",
            persistent: true,
          },
        ],
        encounters: [
          {
            id: "aka-ushi-east-gate",
            kind: "massiveBoss",
            profileId: "giant-02-aka-ushi",
            bounds: { x: 1120, y: 0, w: 1080, h: 360 },
            activationX: 1210,
            cameraLock: true,
            visibleArenaGates: ["arena-barrier-west", "arena-barrier-east"],
            completionUnlocks: ["road-to-castle"],
          },
        ],
      },

      "castle-lower-court": {
        id: "castle-lower-court",
        chapterId: "castle",
        label: "Cour basse du château",
        zoneKind: "castle",
        environmentIndex: 2,
        width: 2500,
        minX: 960,
        maxX: 2479,
        cameraMinX: 900,
        routeMetrics: {
          mainRoute: "horizontal",
          mainRouteLength: 1420,
          requiredClimb: 0,
          structuralFloors: 5,
        },
        spawns: {
          villageReturn: { x: 970, y: PLAYER_GROUND_Y, facing: 1 },
          legacyFpsReturn: { x: 1045, y: PLAYER_GROUND_Y, facing: 1 },
          residenceReturn: { x: 1710, y: PLAYER_GROUND_Y, facing: -1 },
          donjonFpsApproach: { x: 2138, y: PLAYER_GROUND_Y, facing: 1 },
        },
        groundSegments: [
          {
            id: "lower-court-ground",
            x: 900,
            y: HORIZONTAL_GROUND_Y,
            w: 1600,
            h: 60,
            collision: "solid",
            surface: "tatamiStone",
            routeRole: "main",
          },
        ],
        platforms: [
          {
            id: "castle-tower-lower",
            x: 1000,
            y: 222,
            w: 170,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "tour-chateau",
            surface: "roofTile",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "castle-stair-1",
            x: 1140,
            y: 286,
            w: 78,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "castle-stair-2",
            x: 1146,
            y: 270,
            w: 66,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "castle-stair-3",
            x: 1152,
            y: 254,
            w: 54,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "shoji-gallery",
            x: 1225,
            y: 264,
            w: 170,
            h: 8,
            visualHeight: 24,
            visual: false,
            owner: "mur-shoji",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
        ],
        props: [
          { id: "lower-court-tower", file: "tour-chateau", x: 990, width: 180, layer: "back" },
          { id: "lower-court-stairs", file: "escalier-bois", x: 1140, width: 80, layer: "world" },
          { id: "lower-court-shoji", file: "mur-shoji", x: 1215, width: 190, layer: "back" },
          { id: "lower-court-brazier", file: "brasero-fer", x: 1270, width: 32, layer: "back", bottomY: 294 },
          { id: "lower-court-alcove", file: "alcove-tatami", x: 1450, width: 175, layer: "back" },
          { id: "lower-court-armor", file: "armure-vide", x: 1515, width: 38, layer: "world" },
          { id: "lower-court-door", file: "porte-laquee", x: 1705, width: 170, layer: "back" },
          { id: "lower-court-pillar", file: "pilier-cedre", x: 1910, width: 48, layer: "back" },
          { id: "lower-court-rack", file: "ratelier-vide", x: 1960, width: 78, layer: "world" },
          { id: "lower-court-roots", file: "racines-donjon", x: 2045, width: 80, layer: "world" },
        ],
        portals: [
          {
            id: "return-to-village",
            linkId: "market-castle-road",
            x: 970,
            interactionRange: 54,
            collision: "portal",
            type: "return",
            destination: {
              areaId: "kurokawa-market-east",
              spawnId: "castleReturn",
            },
            state: "open",
            visual: "porte-chateau",
            label: "Route du village",
            prompt: "E — REDESCENDRE AU VILLAGE",
          },
          {
            id: "door-to-residence",
            linkId: "court-residence-door",
            x: 1760,
            interactionRange: 52,
            collision: "solidDoor",
            type: "side",
            destination: {
              areaId: "castle-residence",
              spawnId: "lowerCourtReturn",
            },
            state: "closed",
            visual: "porte-laquee",
            label: "Résidence du daimyō",
            prompt: "E — FAIRE COULISSER LA PORTE",
          },
        ],
        enemies: [
          { id: "court-guard-01", roster: "special", x: 1398, y: 276, facing: -1 },
          { id: "court-guard-02", roster: "miniboss", x: 1430, y: 276, facing: -1 },
          { id: "court-guard-03", roster: "special", x: 1650, y: 276, facing: -1 },
          { id: "court-guard-04", roster: "special", x: 1870, y: 276, facing: -1 },
          { id: "court-guard-05", roster: "miniboss", x: 2400, y: 276, facing: -1 },
        ],
        pickups: [
          { id: "court-ofuda", x: 1240, y: 266, kind: "ammo", amount: 4 },
          { id: "court-yomogi", x: 1570, y: 266, kind: "health", amount: 28 },
          { id: "court-ofuda-east", x: 2260, y: 266, kind: "ammo", amount: 4 },
        ],
        encounters: [],
      },

      "castle-residence": {
        id: "castle-residence",
        chapterId: "castle",
        label: "Résidence du daimyō",
        zoneKind: "building",
        environmentIndex: 2,
        width: 2400,
        minX: 6,
        maxX: 2379,
        cameraMinX: 0,
        routeMetrics: {
          mainRoute: "horizontalRooms",
          mainRouteLength: 2180,
          requiredClimb: 64,
          structuralFloors: 6,
          storeys: 2,
        },
        spawns: {
          lowerCourtReturn: { x: 120, y: PLAYER_GROUND_Y, facing: 1 },
          donjonReturn: { x: 2200, y: PLAYER_GROUND_Y, facing: -1 },
          archiveReturn: { x: 1480, y: PLAYER_GROUND_Y, facing: 1 },
        },
        groundSegments: [
          {
            id: "residence-ground-floor",
            x: 0,
            y: HORIZONTAL_GROUND_Y,
            w: 2400,
            h: 60,
            collision: "solid",
            surface: "tatami",
            routeRole: "main",
          },
        ],
        platforms: [
          {
            id: "residence-stair-lower",
            x: 620,
            y: 278,
            w: 72,
            h: 8,
            visualHeight: 24,
            tile: "step",
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "residence-stair-upper",
            x: 680,
            y: 254,
            w: 72,
            h: 8,
            visualHeight: 24,
            tile: "step",
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "residence-upper-floor-west",
            x: 744,
            y: 230,
            w: 360,
            h: 8,
            visualHeight: 28,
            tile: "ledge",
            owner: "residence-upper-storey",
            surface: "cedar",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "residence-upper-bridge",
            x: 1104,
            y: 230,
            w: 180,
            h: 8,
            visualHeight: 24,
            tile: "beam",
            owner: "residence-upper-storey",
            surface: "cedar",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "residence-upper-floor-east",
            x: 1284,
            y: 230,
            w: 390,
            h: 8,
            visualHeight: 28,
            tile: "ledge",
            owner: "residence-upper-storey",
            surface: "cedar",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "residence-east-stairs",
            x: 1674,
            y: 258,
            w: 86,
            h: 8,
            visualHeight: 24,
            tile: "step",
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
        ],
        props: [
          { id: "residence-shoji-west", file: "mur-shoji", x: 200, width: 240, layer: "back" },
          { id: "residence-alcove", file: "alcove-tatami", x: 470, width: 190, layer: "back" },
          { id: "residence-stairs", file: "escalier-bois", x: 620, width: 140, layer: "world" },
          { id: "residence-armor", file: "armure-vide", x: 920, width: 42, layer: "world" },
          { id: "residence-screen", file: "paravent-dechire", x: 1180, width: 96, layer: "front", bottomY: 304 },
          { id: "residence-archive-door", file: "porte-laquee", x: 1450, width: 180, layer: "back" },
          { id: "residence-brazier", file: "brasero-fer", x: 1810, width: 34, layer: "back", bottomY: 294 },
          { id: "residence-rack", file: "ratelier-vide", x: 2000, width: 88, layer: "world" },
        ],
        portals: [
          {
            id: "return-to-lower-court",
            linkId: "court-residence-door",
            x: 90,
            interactionRange: 52,
            collision: "solidDoor",
            type: "return",
            destination: {
              areaId: "castle-lower-court",
              spawnId: "residenceReturn",
            },
            state: "open",
            visual: "porte-laquee",
            label: "Cour basse",
            prompt: "E — SORTIR DANS LA COUR",
          },
          {
            id: "archive-fps",
            linkId: "archive-fps",
            x: 1540,
            interactionRange: 48,
            collision: "solidDoor",
            type: "fps",
            mission: "daimyo-archive",
            destination: { missionId: "daimyo-archive" },
            returnDestination: {
              areaId: "castle-residence",
              spawnId: "archiveReturn",
            },
            state: "closed",
            visual: "porte-laquee",
            label: "Archives scellées",
            prompt: "E — ENTRER DANS LES ARCHIVES",
            optional: true,
            persistentEncounterId: "daimyo-archive-secret",
          },
          {
            id: "corridor-to-donjon",
            linkId: "residence-donjon-corridor",
            x: 2260,
            interactionRange: 54,
            collision: "solidDoor",
            type: "side",
            destination: {
              areaId: "castle-donjon",
              spawnId: "residenceReturn",
            },
            state: "closed",
            visual: "porte-chateau",
            label: "Couloir du donjon",
            prompt: "E — OUVRIR LE COULOIR",
          },
        ],
        enemies: [
          { id: "residence-guard-01", roster: "special", x: 360, y: 276, facing: -1 },
          { id: "residence-guard-02", roster: "special", x: 880, y: 206, facing: -1, platformId: "residence-upper-floor-west" },
          { id: "residence-guard-03", roster: "miniboss", x: 1230, y: 276, facing: -1 },
          { id: "residence-guard-04", roster: "special", x: 1430, y: 206, facing: -1, platformId: "residence-upper-floor-east" },
          { id: "residence-guard-05", roster: "special", x: 1980, y: 276, facing: -1 },
        ],
        pickups: [
          { id: "residence-ofuda", x: 790, y: 198, kind: "ammo", amount: 4 },
          { id: "residence-yomogi", x: 1350, y: 266, kind: "health", amount: 28 },
          { id: "residence-tamahagane", x: 1620, y: 198, kind: "tamahagane", amount: 1 },
        ],
        encounters: [],
      },

      "castle-donjon": {
        id: "castle-donjon",
        chapterId: "castle",
        label: "Donjon supérieur",
        zoneKind: "castle",
        environmentIndex: 2,
        width: 2500,
        minX: 6,
        maxX: 2479,
        cameraMinX: 0,
        routeMetrics: {
          mainRoute: "horizontalChambers",
          mainRouteLength: 2240,
          requiredClimb: 86,
          structuralFloors: 7,
          storeys: 3,
        },
        spawns: {
          residenceReturn: { x: 140, y: PLAYER_GROUND_Y, facing: 1 },
          fpsReturn: { x: 1045, y: PLAYER_GROUND_Y, facing: 1 },
          lowerCourtReturn: { x: 2138, y: PLAYER_GROUND_Y, facing: -1 },
          finalCheckpoint: { x: 1860, y: PLAYER_GROUND_Y, facing: 1 },
        },
        groundSegments: [
          {
            id: "donjon-ground-floor",
            x: 0,
            y: HORIZONTAL_GROUND_Y,
            w: 2500,
            h: 60,
            collision: "solid",
            surface: "tatami",
            routeRole: "main",
          },
        ],
        platforms: [
          {
            id: "donjon-stair-1",
            x: 420,
            y: 280,
            w: 76,
            h: 8,
            visualHeight: 24,
            tile: "step",
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "donjon-stair-2",
            x: 480,
            y: 258,
            w: 76,
            h: 8,
            visualHeight: 24,
            tile: "step",
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "donjon-floor-west",
            x: 550,
            y: 236,
            w: 360,
            h: 8,
            visualHeight: 28,
            tile: "ledge",
            owner: "donjon-second-storey",
            surface: "cedar",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "donjon-central-beam",
            x: 910,
            y: 236,
            w: 210,
            h: 8,
            visualHeight: 24,
            tile: "beam",
            owner: "donjon-second-storey",
            surface: "cedar",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "donjon-floor-east",
            x: 1120,
            y: 236,
            w: 380,
            h: 8,
            visualHeight: 28,
            tile: "ledge",
            owner: "donjon-second-storey",
            surface: "cedar",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "donjon-upper-stair",
            x: 1490,
            y: 210,
            w: 92,
            h: 8,
            visualHeight: 24,
            tile: "step",
            owner: "escalier-bois",
            surface: "wood",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
          {
            id: "donjon-upper-gallery",
            x: 1570,
            y: 184,
            w: 330,
            h: 8,
            visualHeight: 28,
            tile: "ledge",
            owner: "donjon-third-storey",
            surface: "cedar",
            collision: "oneWay",
            routeRole: "structuralFloor",
          },
        ],
        props: [
          { id: "donjon-tower", file: "tour-chateau", x: 260, width: 220, layer: "back" },
          { id: "donjon-stairs", file: "escalier-bois", x: 420, width: 150, layer: "world" },
          { id: "donjon-shoji", file: "mur-shoji", x: 720, width: 220, layer: "back" },
          { id: "donjon-armor", file: "armure-vide", x: 1040, width: 42, layer: "world" },
          { id: "donjon-screen", file: "paravent-dechire", x: 1250, width: 98, layer: "back", bottomY: 294 },
          { id: "donjon-roots-west", file: "racines-donjon", x: 1520, width: 96, layer: "world" },
          { id: "donjon-brazier", file: "brasero-fer", x: 1780, width: 36, layer: "back", bottomY: 294 },
          { id: "donjon-final-door", file: "porte-chateau", x: 2110, width: 220, layer: "back" },
        ],
        portals: [
          {
            id: "return-to-residence",
            linkId: "residence-donjon-corridor",
            x: 100,
            interactionRange: 54,
            collision: "solidDoor",
            type: "return",
            destination: {
              areaId: "castle-residence",
              spawnId: "donjonReturn",
            },
            state: "open",
            visual: "porte-chateau",
            label: "Résidence",
            prompt: "E — REVENIR À LA RÉSIDENCE",
          },
          {
            id: "final-donjon-fps",
            linkId: "donjon-fps",
            x: 2190,
            approachX: 2138,
            blockX: 2148,
            interactionRange: 66,
            collision: "solidDoor",
            type: "fps",
            mission: 1,
            destination: { missionId: "kurokawa-donjon" },
            returnDestination: {
              areaId: "castle-donjon",
              spawnId: "fpsReturn",
            },
            state: "closed",
            visual: "porte-chateau",
            label: "Salle du daimyō",
            prompt: "E — AFFRONTER LE DAIMYŌ",
            persistentEncounterId: "daimyo-donjon",
          },
        ],
        enemies: [
          { id: "donjon-guard-01", roster: "special", x: 330, y: 276, facing: -1 },
          { id: "donjon-guard-02", roster: "miniboss", x: 720, y: 212, facing: -1, platformId: "donjon-floor-west" },
          { id: "donjon-guard-03", roster: "special", x: 1180, y: 212, facing: -1, platformId: "donjon-floor-east" },
          { id: "donjon-guard-04", roster: "miniboss", x: 1660, y: 160, facing: -1, platformId: "donjon-upper-gallery" },
          { id: "donjon-guard-05", roster: "special", x: 2020, y: 276, facing: -1 },
        ],
        pickups: [
          { id: "donjon-ofuda", x: 820, y: 204, kind: "ammo", amount: 4 },
          { id: "donjon-yomogi", x: 1450, y: 266, kind: "health", amount: 28 },
          { id: "donjon-cinder", x: 1760, y: 152, kind: "yomiAsh", amount: 1 },
        ],
        checkpoints: [
          {
            id: "donjon-final-checkpoint",
            x: 1860,
            spawnId: "finalCheckpoint",
            persistent: true,
          },
        ],
        encounters: [],
      },
    },
  };

  const MASSIVE_RENDER_DEFAULTS = {
    maxWidthRatio: 0.55,
    maxHeightRatio: 0.62,
    footAnchor: [0.5, 1],
    preserveSourceAspect: true,
    clampToArenaCamera: true,
  };

  function massiveProfile(definition) {
    return {
      ...definition,
      presentationClass: "massive",
      displayLabel: "Boss massif",
      legacyCategory: "giant",
      modePreference: "side",
      render: {
        ...MASSIVE_RENDER_DEFAULTS,
        ...definition.render,
      },
    };
  }

  const KageMassiveBossProfiles = {
    "giant-01-kurogane-warder": massiveProfile({
      id: "giant-01-kurogane-warder",
      name: "Gardien Kurogane",
      silhouette: "armoredHumanoid",
      render: { targetWidthRatio: 0.39, targetHeightRatio: 0.58 },
      collider: { widthRatio: 0.48, heightRatio: 0.84, anchor: [0.5, 1] },
      arena: {
        kind: "gatehouse",
        minimumWidth: 980,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 230,
      },
      phases: [
        { id: "living-lock", healthRange: [1, 0.55], pattern: "body-check-and-short-sweep" },
        { id: "torn-gate", healthRange: [0.55, 0], pattern: "beam-club-and-platform-break" },
      ],
      detachableParts: [
        {
          id: "beam-club",
          weaponId: "poutre-massue-kurogane",
          separateSprite: true,
          attachPhase: "torn-gate",
        },
      ],
    }),

    "giant-02-aka-ushi": massiveProfile({
      id: "giant-02-aka-ushi",
      name: "Aka-Ushi",
      silhouette: "wideQuadruped",
      render: {
        targetWidthRatio: 0.5,
        targetHeightRatio: 0.49,
        maxWidthRatio: 0.55,
        maxHeightRatio: 0.56,
      },
      collider: { widthRatio: 0.78, heightRatio: 0.62, anchor: [0.5, 1] },
      arena: {
        id: "aka-ushi-east-gate-arena",
        zoneId: "kurokawa-market-east",
        encounterId: "aka-ushi-east-gate",
        kind: "outdoorRoad",
        bounds: { x: 1120, y: 0, w: 1080, h: 360 },
        playerSpawnId: "bossCheckpoint",
        bossSpawn: { x: 1880, y: 218, facing: -1 },
        horizontal: true,
        cameraLock: true,
        visibleClosingProps: ["arena-barrier-west", "arena-barrier-east"],
        destructibleProps: ["arena-cart", "arena-hay"],
        completionUnlocks: ["road-to-castle"],
      },
      phases: [
        {
          id: "plague-yoke",
          label: "Joug de quarantaine",
          healthRange: [1, 0.5],
          pattern: "telegraphed-horizontal-charge",
          attacks: ["horn-charge", "yoke-sweep", "front-stomp"],
          stunCondition: "charge-collides-with-arena-barrier",
          exposedWeakPointIds: ["yoke-straps"],
        },
        {
          id: "freed-beast",
          label: "Bête affolée",
          healthRange: [0.5, 0],
          pattern: "short-charge-and-back-kick",
          attacks: ["short-charge", "back-kick", "double-stomp"],
          speedMultiplier: 1.28,
          detachedPartIds: ["bladed-yoke"],
          exposedWeakPointIds: ["hind-legs"],
        },
      ],
      weakPoints: [
        {
          id: "yoke-straps",
          attachTo: "shoulders",
          phaseIds: ["plague-yoke"],
          damageMultiplier: 1.7,
          postureDamageMultiplier: 2.2,
          activeWindow: "after-failed-charge",
          destroysPartId: "bladed-yoke",
        },
        {
          id: "hind-legs",
          attachTo: "rearLegs",
          phaseIds: ["freed-beast"],
          damageMultiplier: 1.4,
          activeWindow: "during-back-kick-recovery",
        },
      ],
      detachableParts: [
        {
          id: "bladed-yoke",
          weaponId: "joug-tranchant-aka-ushi",
          separateSprite: true,
          attachPoint: "neckRig",
          detachTransition: "phase-2",
          detachedCollision: "hazard",
          persistsAfterDetach: true,
        },
      ],
    }),

    "giant-03-take-mori": massiveProfile({
      id: "giant-03-take-mori",
      name: "Take-Mori",
      silhouette: "tallHumanoid",
      render: { targetWidthRatio: 0.36, targetHeightRatio: 0.6 },
      collider: { widthRatio: 0.45, heightRatio: 0.88, anchor: [0.5, 1] },
      arena: {
        kind: "bambooClearing",
        minimumWidth: 1050,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 240,
      },
      phases: [
        { id: "bare-hands", healthRange: [1, 0.6], pattern: "palms-and-forearms" },
        { id: "bamboo-ram", healthRange: [0.6, 0], pattern: "horizontal-ram-charge" },
      ],
      detachableParts: [
        {
          id: "bamboo-ram",
          weaponId: "belier-bambou-take-mori",
          separateSprite: true,
          attachPhase: "bamboo-ram",
        },
      ],
    }),

    "giant-04-enjin-bozu": massiveProfile({
      id: "giant-04-enjin-bozu",
      name: "Enjin-Bōzu",
      silhouette: "heavyHumanoid",
      render: { targetWidthRatio: 0.41, targetHeightRatio: 0.57 },
      collider: { widthRatio: 0.54, heightRatio: 0.86, anchor: [0.5, 1] },
      arena: {
        kind: "templeCourt",
        minimumWidth: 980,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 230,
      },
      phases: [
        { id: "contained-embers", healthRange: [1, 0.45], pattern: "palms-and-ground-smash" },
        { id: "burning-bell", healthRange: [0.45, 0], pattern: "segmented-flail-sweeps" },
      ],
      detachableParts: [
        {
          id: "bell-flail",
          weaponId: "fleau-cloche-enjin",
          separateSprite: true,
          composition: {
            mode: "segmentedChain",
            linkSpriteId: "chain-link-iron",
            handleSpriteId: "chain-handle-wood",
            endSpriteId: "bell-weight-enjin",
          },
        },
      ],
    }),

    "giant-05-numa-no-oyakata": massiveProfile({
      id: "giant-05-numa-no-oyakata",
      name: "Numa-no-Oyakata",
      silhouette: "wideHumanoid",
      render: { targetWidthRatio: 0.46, targetHeightRatio: 0.57 },
      collider: { widthRatio: 0.62, heightRatio: 0.82, anchor: [0.5, 1] },
      arena: {
        kind: "riverBank",
        minimumWidth: 1080,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 225,
      },
      phases: [
        { id: "drowned-body", healthRange: [1, 0.55], pattern: "grabs-and-body-slams" },
        { id: "domain-anchor", healthRange: [0.55, 0], pattern: "anchor-pulls-and-sweeps" },
      ],
      detachableParts: [
        {
          id: "river-anchor",
          weaponId: "ancre-riviere-numa",
          separateSprite: true,
          attachPhase: "domain-anchor",
        },
      ],
    }),

    "giant-06-kinoko-haha": massiveProfile({
      id: "giant-06-kinoko-haha",
      name: "Kinoko-Haha",
      silhouette: "wideOrganic",
      render: { targetWidthRatio: 0.48, targetHeightRatio: 0.55 },
      collider: { widthRatio: 0.66, heightRatio: 0.8, anchor: [0.5, 1] },
      arena: {
        kind: "quarantineGarden",
        minimumWidth: 1000,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 220,
      },
      phases: [
        { id: "spore-growths", healthRange: [1, 0.5], pattern: "space-control-and-sweep" },
        { id: "broken-growths", healthRange: [0.5, 0], pattern: "short-rush-and-incense-cloud" },
      ],
      detachableParts: [
        {
          id: "spore-censer",
          weaponId: "encensoir-spores-kinoko",
          separateSprite: true,
        },
      ],
    }),

    "giant-07-shiro-kabuto": massiveProfile({
      id: "giant-07-shiro-kabuto",
      name: "Shiro-Kabuto",
      silhouette: "lowWide",
      render: { targetWidthRatio: 0.55, targetHeightRatio: 0.44 },
      collider: { widthRatio: 0.8, heightRatio: 0.66, anchor: [0.5, 1] },
      arena: {
        kind: "riceTerrace",
        minimumWidth: 1120,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 190,
      },
      phases: [
        { id: "closed-shell", healthRange: [1, 0.48], pattern: "guard-and-low-charge" },
        { id: "cracked-shell", healthRange: [0.48, 0], pattern: "fast-lateral-rushes" },
      ],
      detachableParts: [
        {
          id: "shell-shield",
          weaponId: "bouclier-carapace-shiro",
          separateSprite: true,
          detachTransition: "phase-2",
        },
      ],
    }),

    "giant-08-nuno-kyojin": massiveProfile({
      id: "giant-08-nuno-kyojin",
      name: "Nuno-Kyojin",
      silhouette: "tallLimb",
      render: { targetWidthRatio: 0.36, targetHeightRatio: 0.62 },
      collider: { widthRatio: 0.42, heightRatio: 0.9, anchor: [0.5, 1] },
      arena: {
        kind: "prisonYard",
        minimumWidth: 1100,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 245,
      },
      phases: [
        { id: "bound-arms", healthRange: [1, 0.55], pattern: "chain-drag-and-grab" },
        { id: "broken-manacles", healthRange: [0.55, 0], pattern: "long-arm-slams" },
      ],
      detachableParts: [
        {
          id: "prison-chain",
          weaponId: "chaines-menottes-nuno",
          separateSprite: true,
          detachTransition: "phase-2",
          composition: {
            mode: "segmentedChain",
            linkSpriteId: "chain-link-iron",
            startSpriteId: "manacle-left",
            endSpriteId: "manacle-right",
          },
        },
      ],
    }),

    "giant-09-ganseki-otoko": massiveProfile({
      id: "giant-09-ganseki-otoko",
      name: "Ganseki-Otoko",
      silhouette: "armoredHumanoid",
      render: { targetWidthRatio: 0.44, targetHeightRatio: 0.58 },
      collider: { widthRatio: 0.58, heightRatio: 0.86, anchor: [0.5, 1] },
      arena: {
        kind: "quarryFloor",
        minimumWidth: 1080,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 230,
      },
      phases: [
        { id: "stone-armor", healthRange: [1, 0.52], pattern: "armored-advance" },
        { id: "quarry-breaker", healthRange: [0.52, 0], pattern: "hammer-terrain-breaks" },
      ],
      detachableParts: [
        {
          id: "quarry-hammer",
          weaponId: "marteau-carriere-ganseki",
          separateSprite: true,
          attachPhase: "quarry-breaker",
        },
      ],
    }),

    "giant-10-yomi-no-kanrei": massiveProfile({
      id: "giant-10-yomi-no-kanrei",
      name: "Yomi-no-Kanrei",
      silhouette: "finalHumanoid",
      render: { targetWidthRatio: 0.46, targetHeightRatio: 0.62 },
      collider: { widthRatio: 0.58, heightRatio: 0.88, anchor: [0.5, 1] },
      arena: {
        kind: "yomiGate",
        minimumWidth: 1280,
        horizontal: true,
        cameraLock: true,
        requiredCeilingClearance: 250,
      },
      phases: [
        { id: "regent", healthRange: [1, 0.66], pattern: "four-arm-unarmed-combos" },
        { id: "black-nodachi", healthRange: [0.66, 0.32], pattern: "nodachi-sweeps" },
        { id: "broken-regency", healthRange: [0.32, 0], pattern: "desperate-mixed-combos" },
      ],
      detachableParts: [
        {
          id: "yomi-nodachi",
          weaponId: "nodachi-geant-yomi",
          separateSprite: true,
          attachPhase: "black-nodachi",
        },
      ],
    }),
  };

  const host = typeof window !== "undefined" ? window : globalThis;
  host.KageLevels = KageLevels;
  host.KageMassiveBossProfiles = KageMassiveBossProfiles;

  if (typeof module !== "undefined" && module.exports) {
    module.exports = {
      KageLevels,
      KageMassiveBossProfiles,
    };
  }
})();
